### ISSUE TITLE
Bank filtering showing incorrect salve ammy

### ISSUE THREAD

**Issue by SieBrum** [dillydill123/inventory-setups#10]
Currently, the bank fiter interface shows both salve ammys. This might result in taking and dropping the (ei) version at ToB or taking the (e) version to CoX

![image](https://user-images.githubusercontent.com/14212955/72277027-7c9a3600-3631-11ea-8f4d-8cd3e0a550fb.png)

**Comment by dillydill123** [comment]
Try using variation mapping. This should only make it so the amulet you want will show up. It will also hide the other potions besides the 4 dose.
