### ISSUE TITLE
Suggestion: Downgrade options in gear

### ISSUE THREAD

**Issue by DivineInsanity** [dillydill123/inventory-setups#100]
Love the plugin, I currently use it to help share setups with my group of mates / small clan.

The hardest part of it is giving people a setup from my own use case (which is max or close to max gear) and having to kind of tell them everything in the notes to downgrade / in the messages to them.

I've always thought it would be awesome if you could assign "multiple" items per slot, and have them ordered so that you can downgrade through them. So for example a melee boss where Inquis is BiS, then Bandos, then Fighter Torso you could have those 3 items, and they could easily toggle down to "whats the next best suggestion" and see if they have that. Without just having to gear the tab, replace what slots they dont have with their best, and then manually update all the slots / invent items to it.

**Comment by dillydill123** [comment]
I'm sorry but I don't think I'm interested in implementing something like this. There are a lot of things to consider, like how to add new items, how to show downgraded items, etc etc. I think it's best if people just import, and downgrade based on the items. Btw, you can edit a setup by right clicking slots and choosing update from ... This should make it easier to downgrade.

See here: https://github.com/dillydill123/inventory-setups#editing-a-setup
