### ISSUE TITLE
Bug: Having a colon (:) in the Setup Name breaks Layouts

### ISSUE THREAD

**Issue by DivineInsanity** [dillydill123/inventory-setups#102]
Had some setups named for Bandos 9:0 and Zammy 5:0. Found that having the colon present makes the auto-layout not saveable, and also makes duplicate-items in the layout unclickable.

Changing the names to not include the colon fixed the issue. If this special characters causes issues I'd think just blocking it from being usable in the setup names is a good fix.

**Comment by dillydill123** [comment]
Yeah in the backend a colon is used for sorting and filtering. But I'm surprised it's affecting the layout. The bank tag layouts is not part of this plugin so it's probably best to make an issue there.
