### ISSUE TITLE
Toggling noting items sometimes causes the bank filter to disappear

### ISSUE THREAD

**Issue by mrwhisker23** [dillydill123/inventory-setups#104]
See the attached video

https://user-images.githubusercontent.com/7873992/131267911-ad1cda2b-adab-435b-8f0a-03c1e8e57215.mp4

**Comment by dillydill123** [comment]
Do you have bank tags on? See https://github.com/dillydill123/inventory-setups#compatibility-with-bank-tags

**Comment by dillydill123** [comment]
This problem is caused by bank tags. Unfortunately there is nothing I can do because it's actually the bank tags plugin killing the filter because it doesn't detect a bank tag selected.
