### ISSUE TITLE
Duplicate items not clickable when using a colon ':'

### ISSUE THREAD

**Issue by DanCrayons** [dillydill123/inventory-setups#105]
When including a colon in the setup name, it does not let you right click the duplicates to remove them at all.

It will also reset to the auto layout completely.

Imports of each attached
[Working Import.txt](https://github.com/dillydill123/inventory-setups/files/7111847/Working.Import.txt)
[Broken Import.txt](https://github.com/dillydill123/inventory-setups/files/7111848/Broken.Import.txt)

Tested using multiple setups across multiple instances of RuneLite

Runelite Version: 1.7.21.1
OSRS Revision: Rev199
Launcher Version: 2.1.3, 2.1.7

**Comment by dillydill123** [comment]
This is actually an issue with bank tag layouts as far as i'm aware so you'd be better off making an issue with that plugin. Sorry!
