### ISSUE TITLE
Exporting All Setups

### ISSUE THREAD

**Issue by MitchelKohlmann** [dillydill123/inventory-setups#106]
Hi, I love your plugin and I use it alot.

I was wondering if you could make it possible to export all setups at once.
I logged in on my RL account on my laptop but it doesn't transfer the setups i have on my PC.

If this is not possible, could u tell me where i can find the file that contains the JSON data for the setups?

**Comment by dillydill123** [comment]
The setups should be automatically transferred. They are saved to your runelite account after all. But check here https://github.com/dillydill123/inventory-setups/issues/88. There have been requests to add mass import/export so it's something i'll look into.

**Comment by dillydill123** [comment]
Available now in v1.12
