### ISSUE TITLE
Choose item images to represent inventory setups in list

### ISSUE THREAD

**Issue by atheris-viper** [dillydill123/inventory-setups#107]
Similar to choosing an item to represent bank tags or tabs, I think having item icons to represent each inventory setup would make it easier to find a particular setup in the list. Perhaps could be toggleable for those who prefer a text-only list.

**Comment by dillydill123** [comment]
This has been brought up before here: https://github.com/dillydill123/inventory-setups/issues/15

The only way I could really do this would be to add icons only like time tracking does. So I would add a "icon" view which can be toggled like compact view.

**Comment by atheris-viper** [comment]
The way time tracking handles it is pretty much what I have in mind. I could see it either being implemented as an icon-only grid, or as the list view with icons to the left (if there's space). If collapsible categories are added as suggested in #81 I think that'd work nicely with an icon grid.

**Comment by dillydill123** [comment]
This will be in the next update

**Comment by dillydill123** [comment]
Icon mode is now available
