### ISSUE TITLE
The ability to toggle/hide setup edit options

### ISSUE THREAD

**Issue by T7000** [dillydill123/inventory-setups#11]
The entries are really only differentiated by some small text wedged in between a bunch of icons, and to view a setup you have to click the tiny eye icon.

With the edit options hidden you could fit many more setups on screen at a time, so you don't have to scroll to find the entry you're looking for anymore. Then you could have clicking anywhere on the entry take you into the setup.

**Comment by dillydill123** [comment]
This is not a bad idea, but I think having other features like searching or or categorizing setups would make this potentially obsolete. I’ll see about maybe adding a “compact view” that could be toggled

**Comment by dillydill123** [comment]
Planning on making a compact view button that will change it so each setup will hide the buttons. It will just be the name and clicking anywhere will open the setups.

**Comment by dillydill123** [comment]
Compact view was added and merged.
