### ISSUE TITLE
Feature request: remove tab separator

### ISSUE THREAD

**Issue by vikke1234** [dillydill123/inventory-setups#112]
Could you add an option to remove the tab separator similar to the bank tag plugin?

**Comment by dillydill123** [comment]
I took a look at how bank tags does it and it looks easy. I'll add a config option to remove it. BTW the bank tag layouts plugin can be used to setup custom layouts for the filter. It works with inventory setups:

https://github.com/geheur/bank-tag-custom-layouts

**Comment by dillydill123** [comment]
Available now

**Comment by vikke1234** [comment]
cool, thanks
