### ISSUE TITLE
Inventory Setups Breaks Group Storage

### ISSUE THREAD

**Issue by InfernoStats** [dillydill123/inventory-setups#117]
When selecting an inventory setup on the side panel, opening the bank, and then selecting the group storage interface - items are removed with the search bar being selected.

![image](https://user-images.githubusercontent.com/77599829/137523610-889c766b-86a7-4be8-abf0-2542ef8624be.png)

This makes it effectively impossible to use group storage with the solution being to go back to the "overview" panel and not have any specific setup selected.

**Comment by InfernoStats** [comment]
@dillydill123 Here are some observations - it's definitely filtering the items:

1) If you have an empty inventory setup, the same thing happens (as in the picture).

2) If you have an inventory setup open with a single item and then open group storage, it filters as expected.

3) If you have an inventory setup open with two items (one present in group storage and one not) and then open group storage, it filters as expected.

4) If you have group storage open with the panel on overview and then select your setup, it does not filter the group storage until you withdraw or deposit an item.

I'm not sure what the solution here should be, but a config option to not filter group storage sounds like a decent approach as there is no way to look at your items without going into the panel and going back on the setup selection - unlike the bank where you can just press the "View all items tab".

**Comment by dillydill123** [comment]
I'll have to play around with the group storage and find a way to make it more user friendly with inventory setups. A config option to disable filtering in the group storage sounds like a good start. I'll have to checkout bank tags and see what they are up to.

**Comment by dillydill123** [comment]
So it looks like Bank tags just disabled the filtering in group storage unless you specifically do a tag search (which inv setups doesn't support). So I think I will just disable the filtering in group storage as well. Using it my self, I never found myself wanting to use the filtering in the group storage.

https://github.com/runelite/runelite/commit/983d82671ce7855d0d882a4f3db83abcb78e79ac#diff-6ec87109a19c1e1c3fe3d39950f11540a71bb7f9f09e697a12e4076c416b1fbd
