### ISSUE TITLE
Erased Inventory Setups after System Updates Followed by Closing and Reopening Runelite

### ISSUE THREAD

**Issue by Mortilol** [dillydill123/inventory-setups#118]
Hi guys. Whenever there is a system update runelite requires you to close and reopen the client. Twice now since downloading this pluggin, after a system update I log out of my runelite acc, close the runelite interface, and reopen it. Upon reopening it I have missing inventory setups that have just randomly disappeared and it's as if the pluggin has reset to an earlier save state. I made a few inventory setups when I first downloaded the pluggin; like 4. Twice now after a system update, and reopening runelite, I've lost all the setups I've made since then and it reverts back to these 4. I have no idea what the issue could be for why this is happening. Any help would be appreciated! Thank you.

**Comment by dillydill123** [comment]
Does this only happen after system updates?

**Comment by Mortilol** [comment]
Yes that is correct

**Comment by dillydill123** [comment]
Feel free to message me directly on there. I’m not sure if there’s anything I can do for this case. One more question. Are you playing on multiple accounts?

**Comment by dillydill123** [comment]
@Mortilol  did we solve this issue? Please close if so.
