### ISSUE TITLE
Allow for keyboard shortcut or mouse button to return to setups

### ISSUE THREAD

**Issue by T7000** [dillydill123/inventory-setups#12]
When you're viewing a setup you have to click the little arrow on the top right to exit out of it.

I'm not sure if RuneLite allows for it but I'd like the option to go back using my mouse's back/"mouse5" button or some other keyboard shortcut.

**Comment by dillydill123** [comment]
Cool idea. I’ll see if this is possible.

**Comment by dillydill123** [comment]
I added a config option to set a keybind that you can use to go back to the setups panel:

![image](https://user-images.githubusercontent.com/15637422/72690467-b3b58f00-3aea-11ea-9071-5b1b21f08ac4.png)
