### ISSUE TITLE
Suggestion : Add folders

### ISSUE THREAD

**Issue by SplitsDEV** [dillydill123/inventory-setups#120]
Heyy!! Very useful plugin guys!!

So useful that i have like 500 setups.
SOOO, i feel like folders would be a nice addition to the plugin
Itd be useful to organize like ;; boss setups, slayer setups, skilling setups, etc.

I think this has already been suggested, but since it's been a long time since and im not sure if this is being worked on, so yeah just to let you know i would also love to see this added
So yeah thats my suggestion love u guys bye

**Comment by IV20** [comment]
Yes, I would love to see this too! If possible also allowing for folders to have icons too, similar to bank tags plugin.

Also one of my favourite plugins. K thx bye

**Comment by Tech-Freddie** [comment]
yes... 1000 x yes this is such a useful plugin folders /groups would be amazing add-on

**Comment by ashtongraves** [comment]
+1 was looking for this repo just to ask for this lol

**Comment by dillydill123** [comment]
Hey guys this has been the most requested feature for the last year I'm finally working on it. I've made quite a bit of progress recently in my `sections` branch. The current plan is to make a button that will collapse the section when clicked, meaning it will hide the setups that are a part of that "section". Still trying to come up with good designs for the sections and how it will be displayed. Here's a little teaser of what I have so far
![YKQX13OV4L](https://user-images.githubusercontent.com/15637422/175871181-cd7a9ffc-cd01-4f08-ae28-c41b7ee2c3ac.gif)

Is this what you guys are looking for? Like I said still working on the design so buttons and things like that could change.
