### ISSUE TITLE
Plug in download wont save?

### ISSUE THREAD

**Issue by txcardy** [dillydill123/inventory-setups#126]
Everytime I download the "inventory setups" plug in and save some set ups, all works fine. Until I close the Runelight plug in and have to reopen a new Runelite one to play again later.

When I open a new Runelite client to play, the plug it is not there as if I never downloaded it. So I have to download it again everytime i I open a new Runelite client. Its starting to get very annoying having to redownload it and completely re-enter in the information again.

I LOVE the plug in. Wish it was here years ago but I've been away for 4 years. 

Is there something I am doing wrong? I am saving my set ups.

**Comment by dillydill123** [comment]
Are you still facing this issue?
