### ISSUE TITLE
suggestion: bank tags as item

### ISSUE THREAD

**Issue by Odinnh** [dillydill123/inventory-setups#127]
i was setting up a bunch of my profiles, one thing that i kept running into was that it would be great to be able to set up inventory slots to contain bank tags (the ones from the other plugin) 

i tried editing the settings.properties file to change the items to a bank tag but it sadly did not go as hoped.

my suggestion is, if banktags is installed, to be able to right click a loadout slot and "update slot with bank tag" and have it display the first item in that tag.

if that first suggestion does not work, maybe something like the "Food" item in the quest helper plugin

**Comment by dillydill123** [comment]
This feature is not something I'm looking to implement mainly because it could create a dependency on bank tags. I also created this plugin in mind to be used instead of bank tags.
