### ISSUE TITLE
Suggestion: a different way to order fuzzy potions

### ISSUE THREAD

**Issue by SAwesome1018** [dillydill123/inventory-setups#130]
it'd be neat if when you toggled a potion fuzzy, it was able to "stack" on itself, i.e. if i have a prayer potion (4) then a prayer potion (2) it would show the 4 dose until i take it, then switch to the next highest dose.

**Comment by dillydill123** [comment]
Can you explain your example further? I'm not sure if you're talking about bank filtering or highlighting

**Comment by SAwesome1018** [comment]
bank filtering. when you set it to filter potions, i.e. prayer pots or any other pot, with fuzzy toggled, it shows each dose separate, so a space each for (4) dose, (3) dose, (2) dose, and (1) dose. what i propose, is to "stack" potions so that the most full (or least full) is on top, and once you no longer have any, it moves onto the next size. 
![image](https://user-images.githubusercontent.com/54332711/175876824-7a918ec4-1713-43be-a848-2fed122b053f.png) 
so for example, it would show the 35 (4) dose prayer pots, then once they are all removed, it would show the next available dose, which would be the (2) dose, in the same spot, so as to not take up more space

hopefully that's a better explanation, feel free to ask if you have any questions
