### ISSUE TITLE
Bank Filtering not working

### ISSUE THREAD

**Issue by darrenhizon** [dillydill123/inventory-setups#132]
Bank Filtering not working

**Comment by dillydill123** [comment]
Any more details? Did it suddenly stop working? Is it Reproducible?

**Comment by darrenhizon** [comment]
Sorry about this @dillydill123. I didn't read the instructions well. I forgot to turn on the filtering on the inventory setup.

**Comment by whiitehead** [comment]
I'm having the same issue but I am not able to find an option to enable it. I have read through the instructions and the bank is still not filtering. I just installed the plugin so I have never seen it working properly. However, the bank tags plugin does filter properly.

**Comment by dillydill123** [comment]
![image](https://user-images.githubusercontent.com/15637422/193465821-ec05367f-a399-4a76-88da-dabdc8b5777a.png)
It's the filter looking icon for each setup. It's setup independent behavior
