### ISSUE TITLE
Wont display all setups in fixedmode in bank

### ISSUE THREAD

**Issue by moehog0** [dillydill123/inventory-setups#134]
In the bank in fixed mode the menu when right clicking the left corner option doesn't display all of the options once you've reached a certain amount it runs out of screen room? Not sure if this is possible to fix, or like shrink the menu as more options are added but it would be nice ticking the compact option gives a few more options but it still maxes out, for me I use setups for every single thing I do almost in the game so I have lots!
![inventorySetups](https://user-images.githubusercontent.com/54474943/170769157-1cd113c4-5939-4680-85ef-69fa408f6cd1.png)

**Comment by dillydill123** [comment]
This is a problem I've run into before and there is no great solution unfortunately. what I came up with in the past is to allow these to be filtered based on favorites or bank filtered. Please see https://github.com/dillydill123/inventory-setups#configuration-settings at the Show Worn Item Filter option. Either that or move the setups you want to show in the worn items list at the top.

**Comment by dillydill123** [comment]
Perhaps in the future I could try a scrollable menu, that would be an ideal solution.

**Comment by dillydill123** [comment]
Menus are now scrollable from my understanding
