### ISSUE TITLE
SUGGESTION - Ways to filter on main menu

### ISSUE THREAD

**Issue by HaychBe** [dillydill123/inventory-setups#135]
Hi,

Would be a nice idea if we could add a category filter for the layouts. Saving a lot of real estate right off the bat.  I think there a few ways you could approach this.

Example 1 - FOLDERS:

Folder: SKILLING
                     -> GOTR
                     -> Mining
                     -> WT

Folder: PVM
                     -> Cerb
                     -> Cox
                     -> Tob

Example 2 - Categories

When creating an inventory setup. Allow users to define a category for the setup

![image](https://user-images.githubusercontent.com/78485501/173574426-772b8c78-2801-4c75-966b-5fd72f44a040.png)

then in the main menu you can have a filterable drop down menu based off the users category inputs so that when a category is selected all results are filtered based on that result

![image](https://user-images.githubusercontent.com/78485501/173574371-e9bc92b2-239c-4bd7-9a53-af15de7060f9.png)

That being said, great plugin!

**Comment by dillydill123** [comment]
Check the guide for info about sections which are in the latest update
