### ISSUE TITLE
The ability to search through setups

### ISSUE THREAD

**Issue by T7000** [dillydill123/inventory-setups#14]
I'd like to search through the setups like you can with plugins in RuneLite's Configuration panel.

![search RuneLite's Configuration panel](https://user-images.githubusercontent.com/16760518/72681498-8950db00-3ac4-11ea-860a-01be029c3dda.png)

**Comment by dillydill123** [comment]
Definitely doable, will look into it.

**Comment by dillydill123** [comment]
Was able to implement this. Will be available in the next version of the plugin.
