### ISSUE TITLE
Gone after most recent update

### ISSUE THREAD

**Issue by tvanslyke** [dillydill123/inventory-setups#140]
After today's update, the Inventory Setups plugin is missing from the sidebar, from the the installed plugin list, and from the plugin hub.

**Comment by Scape070** [comment]
> After today's update, the Inventory Setups plugin is missing from the sidebar, from the the installed plugin list, and from the plugin hub.

Same

**Comment by flokirr** [comment]
Can concur that indeed, it has gone away.
