### ISSUE TITLE
Favorited Setups order in reverse

### ISSUE THREAD

**Issue by AverageToaster** [dillydill123/inventory-setups#142]
Hello, apologies if this is a dupe or simple user error, but I couldn't find any existing issues with it, and I don't think I've missed any settings.

So for some context, I manually order the list of setups I use, as I like the ease of access on the Worn Items button for quickly swapping between set ups. I recently set up favorited setups to help filter down my list to setups I was using frequently, and noticed an issue in the  side panel list after favoriting a few set ups.

It looks like items that are favorited sort in reverse position order in the side panel. The Worn Items button sorting is fine, and when it is alphabetically sorted, the list appears fine, only when it is default sorted by position does the order get reversed for favorited items.

Picture examples for reference: 

No favorites ordering: 

![image](https://user-images.githubusercontent.com/2941418/177058142-96b39c6c-e112-4365-b415-f59d43badc00.png)

Favorites ordering: 

![image](https://user-images.githubusercontent.com/2941418/177058151-42c5d47d-eb2b-421f-a98b-69ce8a9e8e2f.png)

I've looked into the code and I believe what's going on here is on this line in `moveFavoriteSetupsToTopOfList`: https://github.com/dillydill123/inventory-setups/blob/master/src/main/java/inventorysetups/ui/InventorySetupsPluginPanel.java#L632

Looks like it grabs the full list of setups, and after filtering out and popping out the favorited setups, it pushes the favorites back on top of the list, but because it iterates over the list in order, it ends up pushing the favorites onto the setup list in reversed order.

I don't have a development environment set up for RL plugin development, but if you'd prefer I spin up a PR to fix this myself, I can look into that.

**Comment by dillydill123** [comment]
I think you are correct. Nice find, the fix should be easy enough. I will patch it
