### ISSUE TITLE
Suggestion: Replace item X with Y in all setups

### ISSUE THREAD

**Issue by acdyer** [dillydill123/inventory-setups#143]
Whenever a player makes a direct gear upgrade, like dragon defender to avernic for instance, they would likely want to change all dragon defenders in their setups to avernic defenders. Instead of manually going through dozens, or hundreds, of setups to change each one, it would be great if there was an option to change ALL dragon defenders to avernic defenders, in every setup.

**Comment by dillydill123** [comment]
Makes sense. I could create another right click menu or maybe shift right click so that way its very intentional that you want to do this.

**Comment by Donnyofdoom** [comment]
Bumping this thread as it's a regular pain point for me. Came here to make the exact same suggestion

**Comment by dillydill123** [comment]
This has been added now
