### ISSUE TITLE
Suggestion: Party Plug in addition: Thrall Indicator

### ISSUE THREAD

**Issue by unicowmilker** [dillydill123/inventory-setups#148]
I wanted to suggest the idea of adding a Thrall active symbol to the party plug in to help teammates assist each other in keeping thralls active during fights. I noticed that it would be especially helpful during learning sessions since I was just at Nex and those who were experienced were trying to remind us of thralls on top of all else. Thanks for contributing to the things that make osrs a much more reasonable game to play lol.

**Comment by dillydill123** [comment]
You need to make this issue to the RuneLite repository.
