### ISSUE TITLE
The ability to add icons to setups

### ISSUE THREAD

**Issue by T7000** [dillydill123/inventory-setups#15]
I'd like the option to add icons to entries like RuneLite has for bank tag tabs. Looks great & helps to differentiate each entry.

![RuneLite bank tag tab icons](https://user-images.githubusercontent.com/16760518/72681567-227ff180-3ac5-11ea-8491-91faaad23ffe.png)

**Comment by dillydill123** [comment]
I like it, but where do you think it should show up on the setup panel? I don’t have much real estate to work with.

**Comment by T7000** [comment]
That's true... I'm not sure if you could make the icons tiny and fit them left of the text? Have a placeholder for when there's no icon added yet and make clicking the icon edit the icon itself.

Perhaps there could be an icon view along with/instead of [the compact view you proposed](https://github.com/dillydill123/inventory-setups/issues/11#issuecomment-576014308), eliminate text altogether and just have squares, or icon tabs like in the time tracking panel: 

![image](https://user-images.githubusercontent.com/16760518/72688849-a2c94580-3b0b-11ea-99b8-1a237e2fb357.png)

**Comment by dillydill123** [comment]
Closing for now as I don’t think I will add icons, at least for now.

**Comment by dillydill123** [comment]
Reopening because I've been asked by others to implement this feature.

**Comment by dillydill123** [comment]
Reclosing because I don't see this happening.
