### ISSUE TITLE
Add Smiths gloves (i) as a fuzzy match for Ice gloves

### ISSUE THREAD

**Issue by fuzxi** [dillydill123/inventory-setups#150]
[Smiths gloves (i)](https://oldschool.runescape.wiki/w/Smiths_gloves_(i)) are created by combing Smiths gloves with Ice gloves; they have all the functionality of Ice gloves.

**Comment by dillydill123** [comment]
Done, will be in the next update.

**Comment by dillydill123** [comment]
now available.
