### ISSUE TITLE
Certain items move away from their slot once taken out of the bank

### ISSUE THREAD

**Issue by Crecket** [dillydill123/inventory-setups#158]
There's this weird behavior where certain item placeholders will temporarily move to a seemingly random slot at the top of my bank once I take them out. Like I could be taking out. Easier just to show it so I made a quick gif. As soon as I put the items back in the bank they show on the correct spot again so this isn't completely breaking it for me but worth a bug report 

![inventory bug](https://user-images.githubusercontent.com/7481136/185963482-7f0f83a6-b5a6-4892-9e7e-395885b6ffb1.gif)

**Comment by dillydill123** [comment]
Are you using bank tag layouts?

**Comment by dillydill123** [comment]
I think so. It might be related to the latest update where I optimized the data storage for inv setups. I sent a link to this issue to geheur (Creator of btl) on Discord

**Comment by dillydill123** [comment]
Feel free to make an issue on the bank tag layouts github.
