### ISSUE TITLE
Setup icons are not being saved after closing the client

### ISSUE THREAD

**Issue by Crecket** [dillydill123/inventory-setups#159]
What seems to be happening is that the icon isn't saved correctly and as soon as the client closes it resets to the default primary weapon icon. 

So to reproduce: Set a new icon for a setup, restart Runelite and the icon should be back to the default icon

**Comment by dillydill123** [comment]
Thanks for the issue. I was not saving the iconID correctly so I fixed that.

**Comment by dillydill123** [comment]
Should be fixed now in 1.14.1
