### ISSUE TITLE
Turning on alphabetical sorting shows duplicate entries under the unassigned section

### ISSUE THREAD

**Issue by Crecket** [dillydill123/inventory-setups#160]
If I turn on the alphabetical sorting option and I have 1 or more "real" unassigned setups in that section, I will suddenly see a duplicate entry for every single setup under the unassigned section. As soon as I removed the one unassigned setup I had this bug was gone until I had at least 1 setup in there again which instantly made all the duplicate entries appear.

**Comment by dillydill123** [comment]
I actually made a PR to fix this already but it hasn't been merged yet. Thankfully none of the internal data is affected, it's just incorrect logic when deciding which setups to display in the unassigned section. Thanks for making the issue 👍

**Comment by dillydill123** [comment]
Should be fixed in 1.14.1
