### ISSUE TITLE
Filtering messed up

### ISSUE THREAD

**Issue by elkoyofficial** [dillydill123/inventory-setups#165]
How do I fix this?
![image](https://user-images.githubusercontent.com/63325580/188321573-41c35927-c58e-4994-9ce8-4ea794c8ed26.png)

My old ones are fine. Just all the newly created ones do it.
![image](https://user-images.githubusercontent.com/63325580/188321595-3cdc65a6-8e4c-4d74-9937-bd8f598524ad.png)

**Comment by dillydill123** [comment]
Bank Tag Layouts is the plugin that lets you customize your filtering so you need to make an issue there
