### ISSUE TITLE
Suggestion: Bank Filter, Support Appended * for any amount

### ISSUE THREAD

**Issue by beaudryj** [dillydill123/inventory-setups#166]
I would love if the Bank filter would support any dosage of potion instead of me having to have mixed potions in my invy to mock it out

**Comment by dillydill123** [comment]
https://github.com/dillydill123/inventory-setups#fuzzy-difference Does this solve your issue? Checkout fuzzy difference

**Comment by beaudryj** [comment]
seems like it, curious why you wouldnt have this turned on on known items by default? i.e. have a library of degradable items or potions or pies i.e. as a json or something and then just let people toggle off

**Comment by beaudryj** [comment]
definitely worked though, thank you :)

**Comment by dillydill123** [comment]
In the past i had it as default but I learned more often that opt-in is better than opt-out for this feature.
