### ISSUE TITLE
"Show worn items" only show favorites

### ISSUE THREAD

**Issue by SAwesome1018** [dillydill123/inventory-setups#167]
As someone who has 50+ setups, I think it'd be a decent idea to have the option to make the "Show worn items" button only show the setups I've favorited.

**Comment by dillydill123** [comment]
This already exists in the options https://github.com/dillydill123/inventory-setups#Configuration-Settings under Show Worn Item Filter

**Comment by SAwesome1018** [comment]
did not see that, sorry for not looking harder
