### ISSUE TITLE
Locking a divine rune pouch with a trouver parchment breaks bank rune filtering and rune display in plugin

### ISSUE THREAD

**Issue by chris-bowen** [dillydill123/inventory-setups#174]
![image](https://user-images.githubusercontent.com/10050432/204991804-cbd0aa36-6029-4841-8b84-fad5711554d9.png)

After using a trouver parchment on a divine rune pouch, the display no longer works correctly and the bank filtering does not work. Not tested with regular three slot rune pouch.

**Comment by chris-bowen** [comment]
Not a Java or plugin developer, so could be more to it than this, but skimming the code it may be as simple as adding ItemID.DIVINE_RUNE_POUCH_L to the RUNE_POUCH_DIVINE_IDS list in InventorySetupsRunePouchPanel.java

**Comment by dillydill123** [comment]
There's a pull request already for this, but I'm not able to test this. If you're able to setup the development environment and test it that would be helpful https://github.com/dillydill123/inventory-setups/pull/171

**Comment by timrwwatson** [comment]
Any movement on this, as it's still an issue and itd be cool to get a fix for this :)

**Comment by dillydill123** [comment]
I've created an update request about a week ago but it has not been approved by the RL devs yet

**Comment by dillydill123** [comment]
This should be in now, let me know if there are any problems with it. If you had a locked pouch before you might need to re add the pouch to your setup
