### ISSUE TITLE
BUG: Setups don't save when playing 2 clients

### ISSUE THREAD

**Issue by IromTypo** [dillydill123/inventory-setups#177]
Does the plugin save when you close your client?

**Comment by dillydill123** [comment]
Yes, the plugin data (and all plugin data) saves when you close RuneLite gracefully (meaning it doesn't crash). If you are logged into RuneLite, using the same session file will cause an issue and data will not be saved correctly. The plugin should work fine with multiple clients in my experience, but you need to use separate session files (with different RuneLite accounts)

**Comment by dillydill123** [comment]
Are you still experiencing this issue?

**Comment by IromTypo** [comment]
No, it was shutting down while OSRS was still running! Thank you, sorry for not replying.
