### ISSUE TITLE
Place Icon before 'Info' tab.

### ISSUE THREAD

**Issue by JZomerlei** [dillydill123/inventory-setups#18]
I think the Runelite Info tab should be the most bottom tab on the client. Other plugin hub items come before it but this one comes after it.

![image](https://user-images.githubusercontent.com/14265490/74153431-9900a280-4bde-11ea-9ba0-846028b92a3d.png)

Great plugin!

**Comment by dillydill123** [comment]
Set the priority to six and it has been merged.
