### ISSUE TITLE
Bug: when switching to/from notes it combines tabs

### ISSUE THREAD

**Issue by Stickaplex** [dillydill123/inventory-setups#182]
When you switch to/from withdrawing as notes, it will temporarily combine whichever tab you were previously on (i think) with your custom setup. 

To fix you just need to refilter it which is annoying

**Comment by dillydill123** [comment]
Checkout https://github.com/dillydill123/inventory-setups/issues/29 for an explanation on why this occurs. It's because of bank tags. Can't do much about it
