### ISSUE TITLE
Bug/Feature Request: Change Behavior of + button

### ISSUE THREAD

**Issue by Kinomora** [dillydill123/inventory-setups#183]
Before I made any section / collapsable categories the + button always added a new setup when left-clicked. Now that I have added a section, the left-click behavior is to add a new section rather than add a new setup.
There does not seem to be any way to change this behavior in the settings and it's kind of frustrating. Please either add a config option or make the + button always add a new setup rather than a new section.

**Comment by dillydill123** [comment]
The + button changes behavior based on if you have section view or not. You can also right click the + button and it will let you select between a section and inventory setup. I think splitting them up into separate buttons might be better though

**Comment by dillydill123** [comment]
This has since changed so it opens a menu which makes you choose which to create.
