### ISSUE TITLE
Hotkey if bank open

### ISSUE THREAD

**Issue by Swepz** [dillydill123/inventory-setups#185]
First of all, fantastic plugin!

I'm trying to use the hotkeys for filtering, which has been a fantastic experience, except for one thing. I mostly play on a laptop, using a tiling window manager, and do not have that many "free" hotkeys to disable when using the plugin.

Current behavior: Set hotkey's 'Z', 'X', and 'C' for filtering different setup options will disable these keys in-game, meaning that these keys cannot be used for typing in chat.

Expected behavior: Set any hotkey for filtering different active setup options when the bank is opened or can create uncommon combination alternatives, e.g., "Ctrl+Shift+W." or hotkeys only work when "Press Enter to Chat..." is active.

**Comment by dillydill123** [comment]
I was able to add and test it easily, should be in the next update.

**Comment by dillydill123** [comment]
It's in the current update. Reopen if there are any issues

**Comment by Swepz** [comment]
Seems to work perfectly, nice work!
