### ISSUE TITLE
Export bug

### ISSUE THREAD

**Issue by Spuddex** [dillydill123/inventory-setups#186]
So if you export a really big setup like this https://imgur.com/DLC4Deb the person that receives it will look like this https://imgur.com/a/Q1SYaIk. If you go to preview auto layout it won't make it look like the original. Our sorting mode is set to default. I think something breaks cause its soo many items.

**Comment by dillydill123** [comment]
I think this is an issue for Bank Tag Layouts since that's the plugin making the layout for you, not Inventory Setups
