### ISSUE TITLE
BUG: Visual artifacting of items when using highlighting

### ISSUE THREAD

**Issue by Yamnasm** [dillydill123/inventory-setups#187]
![image](https://user-images.githubusercontent.com/26772570/218580528-da557eb2-8041-49a5-8b7c-3afa651acd73.png) ![image](https://user-images.githubusercontent.com/26772570/218581671-44d993a0-2a2a-4625-8c13-2da42d87a05b.png)

Above images shows opaque sprites that appear behind (or in front of) intended cell image. Opaque sprites are of items that are within the Inventory collection.

Bug appears irregularly when moving items to and from inventory. Bug is repeatable with higher chance when Depositing Inventory into bank

Visual bug disappears when tabbing out of and back into RuneLite client.

**Comment by dillydill123** [comment]
Do you have your highlight color using a certain opacity? I think this related to this issue: https://github.com/dillydill123/inventory-setups/issues/53

**Comment by Yamnasm** [comment]
I was testing using different opacities to find is there is a value that triggers this affect, and I'm noticing that it seems to happen on lower opacities, but maybe that's because I can't see the bug through high opacity.

However, I did see this interesting artifacting:
![image](https://user-images.githubusercontent.com/26772570/221668028-617aaccb-dc0e-4e7d-956d-c4ce28527fb2.png)
The "background" image is the RuneLite logo, which I've not seen before...

From the comments on #53 teleporting definitely triggers this bug more. Each teleport "resets" the highlighting.

I'll experiment more with how to force / clear it or where the images may be coming from but honestly this bug definitely isn't gamebreaking.

**Comment by dillydill123** [comment]
Opacity is fixed now when setting colors, should be fixed when setting new colors
