### ISSUE TITLE
Setups not loaded correctly when using multiple profiles

### ISSUE THREAD

**Issue by Laurens-W** [dillydill123/inventory-setups#192]
I used to have a setup with 2 session files and 2 runelite accounts.
I have converted those to the new profiles setup and I can see a difference in setups in the actual files.
However when I open the interface in runelite only the setups for 1 profile are shown

Top client is my main, bottom is my zerker
![image](https://user-images.githubusercontent.com/16796960/221662138-b618f8f4-a903-4fda-80e4-d63e188741be.png)
in zerker.properties in .runelite/profiles2 the setup contains my zerker gear, like dagonhai robes and blessed d'hide and such under the inventorysetups.setups key.

**Comment by Laurens-W** [comment]
Just realised there's a inventorysetups.setupsV2 key, before I go about manually converting my old setups, are those synced from the runelite account?

**Comment by dillydill123** [comment]
Thanks for letting me know. I probably need to add some code for switching profiles (just like there is code for switching session files). I’ll investigate it this week

**Comment by dillydill123** [comment]
Should be in the latest update. Reopen if there are issues
