### ISSUE TITLE
Option to open the 'opened' setup by left-clicking worn items icon (top left icon in bank)

### ISSUE THREAD

**Issue by Gollum69** [dillydill123/inventory-setups#193]
Currently, whatever setup is opened you still need to right-click the worn items icon to be able to view it again, if you've clicked onto another tab after it opening that setup when you open the bank, but since the setup has been declared open it would be nice if you could quickly access the setup again by just left-clicking the icon instead of closing/opening the bank or right-clicking the icon and choosing the setup.

**Comment by dillydill123** [comment]
You can setup hotkeys to "refilter" the bank. I think this should be sufficient for your use case.
