### ISSUE TITLE
hotkeys no longer working outside of bank interface

### ISSUE THREAD

**Issue by Orimazer** [dillydill123/inventory-setups#194]
hi,
the recent change to hotkeys only working in bank is kinda disruptive to how i use the plugin. i most often use the hotkey to close the current setup when not at a bank, but rather while running to the bank, opening a new setup before im in the bank interface. while this is still possible by clicking the back icon, it is a lot more cumbersome. would it be possible for this change to be reverted, or put on an optional toggle?

**Comment by dillydill123** [comment]
In hindsight I should have made this a toggle. I can add this

**Comment by Orimazer** [comment]
wonderful, thank you
i'd also like to express my general gratitude for this plugin, can't imagine playing without it now

**Comment by dillydill123** [comment]
It's in now
