### ISSUE TITLE
[Bug] Return to setups hotkey not working even inside bank

### ISSUE THREAD

**Issue by DoilCoding** [dillydill123/inventory-setups#195]
The "return to setups hotkey" does not seem to be working anymore, even whilst the bank is open.
Attempted restarted runelite, rebinding it to something else but nothing is working when it use to work before this update.

**Comment by dillydill123** [comment]
Do you have another hotkey with the same key? From a different plugin? I'm unable to reproduce it. Try changing the key turning the plugin off and on.

**Comment by DoilCoding** [comment]
Even turning off the plugin did not fix it, but after restarting the game twice it has since fixed itself.
Might just be a weird java hitchup or something, thanks for the reply though am loving the plugin.
