### ISSUE TITLE
Filtering New Speedrunning Graceful

### ISSUE THREAD

**Issue by Its-Aloha** [dillydill123/inventory-setups#199]
Hello! I just wanted to preface this post by saying how much I really appreciate this plguin! - This is such a minor issue, but thought I'd post anyways.

So I recently got the new speedrunning graceful and noticed that the plugin doesn't recognize the speedrunning graceful as graceful during the bank filtering. 

Like it will filter the setup and the graceful will be in the filter, although even if the graceful is in the bank it still has the "white outline" around it as its missing. 

Just figured I'd post this hoping for maybe advice if I'm doing something wrong, or an update in the future! Thanks so much!

**Comment by dillydill123** [comment]
I have to look at what's going on with the speed running graceful, but I think fuzzy should work on it for the time being.

**Comment by Its-Aloha** [comment]
Thanks! - So the fuzzy does work - Although I have 11 sets of graceful and if I use the Fuzzy it pulls all of the sets into the same grouping which kind of sucks.

**Comment by dillydill123** [comment]
I found the issue. It's actually something in RuneLite that they recently fixed. So the next version of RuneLite should cause it to work as expected. See https://github.com/runelite/runelite/pull/16404

**Comment by dillydill123** [comment]
This should be fixed now, but if it's not reopen
