### ISSUE TITLE
OSRS Invy collab

### ISSUE THREAD

**Issue by while-loop** [dillydill123/inventory-setups#20]
Hey! I've stumbled across your plugin and would like to get your thoughts on collaborating with my tool OSRS Invy. 

I currently have the front and backend mostly complete and needed to find a way to integrate it into runelite and I think this plugin is perfect for that. 

I was thinking the export could have an option to share to OSRS Invy. And the OSRS Invy would also have an export to `Inventory Setup` button. 

As for authentication, I was thinking of a supplied API key via the plugin's config menu. 

Here's an example loadout. ( Im still using the generated GCP domain, but would get an official domain w/ SSL before integrating into the plugin)

https://osrsinvy-web-5wv3uzemha-uc.a.run.app/l/dc632fed-bfae-45b2-92f1-515723e3e06b

I do intend the project to be open source, but it's private for now.

**Comment by dillydill123** [comment]
Sounds interesting, although I'm hesitant to use any REST service directly from my plugin right now. The import/export feature is JSON so at the very least copying to and from the plugin should be easy enough.

**Comment by while-loop** [comment]
Right. Now that I think about it, crystal lmathlabs and twitch (this I know of) is the only non-runelite plugin that sends info out.

I'll probably have to make a simple plugin to test if it's feasible or if Adam declines it or not.
