### ISSUE TITLE
BUG: Switching to "Withdraw as Note" sometimes adds items to the inventory setup

### ISSUE THREAD

**Issue by zang227** [dillydill123/inventory-setups#201]
A lot of the time but not always switch the withdraw type will add all the items from whatever the selected inventory tab is underneath the setups.

Video of the bug: https://www.youtube.com/watch?v=FRJDY5IaeV4

**Comment by dillydill123** [comment]
Do you have the plugin bank tags on? See https://github.com/dillydill123/inventory-setups/issues/29. Try turning off bank tags and see if the issue is resolved. There's not much I can do about it
