### ISSUE TITLE
Turn bank filtering off

### ISSUE THREAD

**Issue by anthony4987** [dillydill123/inventory-setups#202]
The button to turn it on doesn't turn it off? I want to hide setups from the right click menu that i don't use often.

**Comment by dillydill123** [comment]
Can you elaborate? I'm not sure what you're referring to

**Comment by anthony4987** [comment]
the funnel icon that enables bank filtering does not turn it off. The setup stays in the show worn items right click menu. 
![image](https://user-images.githubusercontent.com/128991774/233778381-c1708048-85fb-4388-8088-f5cb9a7564b7.png)
![image](https://user-images.githubusercontent.com/128991774/233778396-c002942e-d0c2-4a8f-8bcf-118b87d6694c.png)

**Comment by dillydill123** [comment]
You need to go to the config and enable "Filtered" for the shown worn items option
