### ISSUE TITLE
How to change text alignment?

### ISSUE THREAD

**Issue by dandyandy35** [dillydill123/inventory-setups#208]
My phone dropped on my keyboard and apparently pressed some combination of keys that changed text alignment in the notes section. All of my inventory setups now have the text aligned right. Not a game ender, but definitely a nuisance as I am used to aligned left text. Does anyone know the key combinations to change text alignment back to left?

![Text Alignment](https://user-images.githubusercontent.com/132415874/235817897-2c9e3b01-7730-4244-8caf-1336ea80d5dc.png)

**Comment by dandyandy35** [comment]
Restarting Runelite appeared to fix the issue

**Comment by dillydill123** [comment]
Looks like `Ctrl + Shift + o` is what causes this

**Comment by dandyandy35** [comment]
That in fact works. Thanks for they quick response!
