### ISSUE TITLE
Suggession: make a premade gear setups like for bossing or other well known activities

### ISSUE THREAD

**Issue by hiro011** [dillydill123/inventory-setups#211]
this is just a suggestion to add a premade setup gears. i was searching for gear setup pack like tile marker pack but didn't find any plugin so I was hoping if u guys can add something like that.

**Comment by dillydill123** [comment]
It's really difficult for something like this because every account progression is different, and needs to be updated when new content comes out

**Comment by hiro011** [comment]
fair point
tys for replay
