### ISSUE TITLE
Opening a setup directly from bank after plugin update causes incorrect panel layout

### ISSUE THREAD

**Issue by Nightfirecat** [dillydill123/inventory-setups#212]
To reproduce:

1. Launch the client after the plugin has updated via the plugin hub
2. Enter the bank and select a setup via right-clicking the "Show worn items" button
3. Open the Inventory Setups panel
4. Observe the setup name/refresh/back bar is missing at the top, and the patch notes display at the bottom. See images below.

Top:
![Screenshot_20230504_221450](https://user-images.githubusercontent.com/2199511/236382033-5e5d4692-a9d9-46ac-8cf2-03110c61a1b5.png)

Bottom:
![Screenshot_20230504_221516](https://user-images.githubusercontent.com/2199511/236382060-c161bce3-d515-4a7e-9d0e-f62307324d6b.png)

**Comment by Nightfirecat** [comment]
No, opening the sidebar directly brings up the update message alone, as intended. You have to select a setup via the ingame selection interface before opening the sidebar for it to appear--and it doesn't happen again until the next update, of course.

**Comment by Nightfirecat** [comment]
Just commenting here to say this still happens. You can probably reproduce this with some config surgery--set the saved previous version to an earlier one, then follow the steps in OP
![Screenshot_20230802_205247](https://github.com/dillydill123/inventory-setups/assets/2199511/873dbcfe-02c5-4a70-bd74-00d40105b46d)

**Comment by Chelfert** [comment]
Also experiencing this issue. Any idea how to workaround it?

**Comment by dillydill123** [comment]
I forgot to fix this but will get around to it. I assume to work around it just turn off and on the plugin and make sure to open the side panel and select the return to setups button first before using "Show worn items"

**Comment by dillydill123** [comment]
This should be fixed now in 1.18
