### ISSUE TITLE
Have an option to have a setup not appear in the worn items button

### ISSUE THREAD

**Issue by Stickaplex** [dillydill123/inventory-setups#213]
Being able to select which setups will appear in the drop down menu will really help reduce clutter, especially for people like me likes to make a setup for just about everything. 

I know that was probably the idea behind adding the sections as well (huge props btw. thank you!!) but this could probably enhance it even further I feel.

**Comment by dillydill123** [comment]
You can favorite sections or disable the filter on them and then go in the config and try one of these options: 
![image](https://github.com/dillydill123/inventory-setups/assets/15637422/3747c47d-d2df-4124-bb0c-ec2151f56642)
