### ISSUE TITLE
Able to reorganize the order of sections

### ISSUE THREAD

**Issue by Stickaplex** [dillydill123/inventory-setups#214]
Unless I've missed it somewhere I believe the only way to order the sections is to create them in that order. Particularly with sections being added to the worn items menu I feel like this would help with organization quite a bit.

**Comment by Raitab** [comment]
You can right-click on any section and move them up/down, to top or bottom, or to a specific position. I haven't known a time for this not to be true since Sections were added.

**Comment by dillydill123** [comment]
Please check the wiki and try right clicking sections to move them.
