### ISSUE TITLE
Setup section menu entries are in reverse order

### ISSUE THREAD

**Issue by Nightfirecat** [dillydill123/inventory-setups#215]
See below:
![Screenshot_20230513_195822](https://github.com/dillydill123/inventory-setups/assets/2199511/f793996e-1b16-4d6e-9be0-9a9e067cd2c0) ![Screenshot_20230513_195842](https://github.com/dillydill123/inventory-setups/assets/2199511/d4a7bb0a-dd99-4570-a512-50d1f1534bac)

I'd expect slayer entries to be:
* Main DKs
* Main Sire
* ...

**Comment by RL-User** [comment]
Came here to file the same issue but I see there already is one. Hopefully if the developer finds time, they can fix this because I love the section feature they added

**Comment by dillydill123** [comment]
Turns out they weren't in reverse order necessarily. They were in the original inventory setup order which doesn't match the order they appear in sections. I added changes so it will match the side panel no matter if alphabetical order is set or not. Was a bit trickier than I thought

**Comment by dillydill123** [comment]
Fixed
