### ISSUE TITLE
Ava's Assembler missing from Item Search

### ISSUE THREAD

**Issue by Gollum69** [dillydill123/inventory-setups#218]
I've noticed the standard Ava's assembler doesn't appear on the item search when inputting items onto the setups. I will include a screenshot of the items that are displayed. The item that looks like the assembler is the broken version.

https://i.imgur.com/3ZKKB3N.png

**Comment by Raitab** [comment]
This is a problem with RuneLite's ChatboxItemSearch somewhere in here
https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/game/chatbox/ChatboxItemSearch.java#L296

Other plugins also use this functionality and the result is the same.

I might suggest moving this issue to the runelite repository.

**Comment by Gollum69** [comment]
I will do that thanks

**Comment by Gollum69** [comment]
Been informed that is now fixed and presumably will be part of the next RuneLite update
