### ISSUE TITLE
feature request: Granite cannonball should appear if "Toggle fuzzy" is selected on normal cannonball

### ISSUE THREAD

**Issue by MosheBenZacharia** [dillydill123/inventory-setups#219]

**Comment by dillydill123** [comment]
Use a granite cannonball instead and mark it as fuzzy

**Comment by MosheBenZacharia** [comment]
hmm, doesn't seem to work 
<img width="996" alt="image" src="https://github.com/dillydill123/inventory-setups/assets/12495920/01dba4ce-66af-4b06-973b-f9daee62fb10">

**Comment by dillydill123** [comment]
Do you have regular cannon balls in your bank? Granite cannonball -> regular cannon ball was the first variation mapping I added.

https://github.com/dillydill123/inventory-setups/blob/master/src/main/java/inventorysetups/InventorySetupsVariationMapping.java#L35

**Comment by MosheBenZacharia** [comment]
yep definitely 

<img width="456" alt="Screenshot 2023-07-18 at 4 51 35 PM" src="https://github.com/dillydill123/inventory-setups/assets/12495920/4a94a210-34f0-4ffa-bd3c-5bfdea8da205">

**Comment by MosheBenZacharia** [comment]
maybe you accidentally linked to this one from cabin fever? https://oldschool.runescape.wiki/w/Cannon_ball is there an item id without the underscore?

**Comment by dillydill123** [comment]
I think I am using the wrong item ID

**Comment by dillydill123** [comment]
should be fixed now

**Comment by MosheBenZacharia** [comment]
thanks dill!
