### ISSUE TITLE
Could inventory setups be added to the bank interface where tag tabs are?

### ISSUE THREAD

**Issue by tonyp12345** [dillydill123/inventory-setups#220]
![mspaint_Xx088h21Hy](https://github.com/dillydill123/inventory-setups/assets/82453152/9c97b1ec-7759-4adb-990b-09ecfe10fb56)
![RuneLite_HmjWUKRFqP](https://github.com/dillydill123/inventory-setups/assets/82453152/19d69243-8117-4018-a4cf-d7c5052a078a)

**Comment by dillydill123** [comment]
I've considered this a lot of times but It's a lot of effort and it would make the plugin further incompatible with bank tags. For this reason I don't want to implement this
