### ISSUE TITLE
Easier way to mass duplicate items

### ISSUE THREAD

**Issue by Gollum69** [dillydill123/inventory-setups#222]
Currently if you replace a type of food or potion you will have to keep duplicating items and placing them back into the worn items setup, and it can become quite tedious, it would be nice if perhaps another popup appears asking how many of this item do you want duplicated, or just multiple options that says duplicate item, duplicate item-5, duplicate item-X, etc, or potentially a default option in the settings that the user can choose to duplicate a set amount of times everytime

**Comment by dillydill123** [comment]
Is this for bank tag layouts? I think you mean to make the issue there

**Comment by Gollum69** [comment]
Probably. I'll post it there thanks
