### ISSUE TITLE
BUG: Clicking 'withdraw as note' removes the bank filter

### ISSUE THREAD

**Issue by Dubious0** [dillydill123/inventory-setups#223]
https://streamable.com/e591al

This happens every time I click to withdraw as note since the recent update.
All plugin settings are default.

**Comment by MosheBenZacharia** [comment]
yeah, this used to happen sometimes but seems like now its a 100% repro rate

**Comment by dillydill123** [comment]
Known issue. Only solution is to disable bank tags plugin

https://github.com/dillydill123/inventory-setups/issues/29

https://github.com/dillydill123/inventory-setups#bank-tags-plugin
