### ISSUE TITLE
Selecting the "Note" option in the bank interface breaks the layout. 

### ISSUE THREAD

**Issue by EliJ91** [dillydill123/inventory-setups#228]
**### Before:**
![image](https://github.com/dillydill123/inventory-setups/assets/59631669/051b419b-94b9-4c67-a8c7-4ab63f468d4e)

**### After:**
![image](https://github.com/dillydill123/inventory-setups/assets/59631669/9dae12fd-2d31-4765-8cb0-cf58705a854b)

**Comment by dillydill123** [comment]
https://github.com/dillydill123/inventory-setups/issues/29 see here. It's due to bank tags being on
