### ISSUE TITLE
Define a prepot/supplies setup

### ISSUE THREAD

**Issue by nds1234** [dillydill123/inventory-setups#229]
Great plugin - was thinking it'd be great if we could define a 'prepot/supplies' inventory that would be appended to all other setups (or maybe include a toggle to indicate whether a setup should include it).  Maybe there's already a way to handle this that I'm missing, but I could see it being a time saver if there isn't.

**Comment by dillydill123** [comment]
There's additional filtered items which will work for your use case but nothing to indicate a standard "prepot/supplies". I don't really plan on adding something like this since additional filtered items can handle it. I know it's not ideal to copy it
