### ISSUE TITLE
Plugin fails to build after flatlaf migration

### ISSUE THREAD

**Issue by YvesW** [dillydill123/inventory-setups#232]
Info:
https://github.com/runelite/runelite/issues/17284
https://discord.com/channels/301497432909414422/419891709883973642/1185657860793847848

After approx mid January the plugin will stop working due to the flatlaf migration.

**Comment by dillydill123** [comment]
Thanks, will take a look

**Comment by YvesW** [comment]
Fixed in https://github.com/dillydill123/inventory-setups/commit/fd4df58d5939f96bcc31eb9f9ea1785b2380cd88
