### ISSUE TITLE
add an option to prevent item dragging

### ISSUE THREAD

**Issue by villecc** [dillydill123/inventory-setups#233]
The plugin included in base RuneLite, called Bank Tags, has an option called "prevent tag tab item dragging".  I would like this in inventory setups, when bank filtering.  As a crutch solution one can use the Anti Drag plugin, but it is annoying as it applies everywhere.

**Comment by dillydill123** [comment]
Can you explain briefly what this does? Might be able to copy over the code, or bank tag layouts might be able to add it

**Comment by Antimated** [comment]
> Can you explain briefly what this does? Might be able to copy over the code, or bank tag layouts might be able to add it

I think he means an option to prevent draggin items inside a inventory setup, so you don't mess up the order :)

**Comment by dillydill123** [comment]
Layouts are now used with inventory setups. So I will close this.
