### ISSUE TITLE
Bug: The bank layout bugs out when you switch to withdrawing items as notes

### ISSUE THREAD

**Issue by Telope** [dillydill123/inventory-setups#234]
Steps to Reproduce:

* Open Bank
* Select a bank tab from the top row (e.g., tab 1)
* Select an inventory setup from the plugin sidebar
* Click the button to withdraw items as notes.

Expected Result:

The inventory setup layout displayed in the bank should remain the same. Items can be withdrawn as noes.

Actual Result:

The inventory setup seems to be merged with the items in tab 1 instead of only showing the items in the inventory setup.

Additional:

* This only happens when a bank tab is selected. If the full bank is shown (i.e., click the infinity symbol in the top left of the bank interface) then the bank tab/inventory setup behaviour is as expected.
* The same issue also happens when switching back from withdraw items as notes to withdraw as items.

**Comment by dillydill123** [comment]
I believe this is because bank tags plugin is on. Nothing can be done about it
