### ISSUE TITLE
Request: Search item in panel to find setups it is in

### ISSUE THREAD

**Issue by Intecpsp** [dillydill123/inventory-setups#235]
If there is a way to do this already, I have not found it. But I'd love to be able to search in the panel for an item and it filters the list of setups based on if that item is in them or not.

Use case: I am migrating from bank tags and layouts to this plugin and since I'm getting rid of the tags, I won't be able to see if I can get rid of an item as easily (if it has tags or not). Being able to search for it would tell me if I can sell the item, or if it is needed. (Keeping up tags and setups is a bear, and I would prefer not to do it)

**Comment by dillydill123** [comment]
@rbbi you are working on some implementation of this? I think the best way would be to have a tag in the search bar like item:<name> and it will find each setup which has the item

**Comment by rbbi** [comment]
> @rbbi you are working on some implementation of this? I think the best way would be to have a tag in the search bar like item: and it will find each setup which has the item

Sounds good, created a PR for this #238

**Comment by dillydill123** [comment]
Done, in 1.18
