### ISSUE TITLE
why is it looking like this , normally its setup to click and dont have to inv mange

### ISSUE THREAD

**Issue by jordion** [dillydill123/inventory-setups#236]
![2024-02-05_20-55-46](https://github.com/dillydill123/inventory-setups/assets/69829069/6d9831db-8a44-4a6e-869c-7cca548686a2)
![9999999999999999999999](https://github.com/dillydill123/inventory-setups/assets/69829069/4931f771-580a-436c-bb90-04410c7161b7)

**Comment by dillydill123** [comment]
I think bank tag layouts was down recently. It should be back to normal
