### ISSUE TITLE
Setups don't seem to be tracking the new Rune Pouch loadouts

### ISSUE THREAD

**Issue by Intecpsp** [dillydill123/inventory-setups#239]
When adding runes to a pouch from the loadout screen, the setup still has them marked as not in the pouch (red).

**Comment by dillydill123** [comment]
can you provide a screenshot or gif?

**Comment by dillydill123** [comment]
I've been able to identify the issue. To fix for now, just move the rune pouch in the inventory or update your inventory somehow

**Comment by dillydill123** [comment]
Fix has been made. Waiting for RL admins to approve and merge: https://github.com/runelite/plugin-hub/pull/5565

**Comment by Intecpsp** [comment]
I'm sorry for the late response, I submitted this issue and then left my computer for the night. I'm glad you have a fix coming for it! Thank you!

**Comment by dillydill123** [comment]
should be fixed now
