### ISSUE TITLE
[Request] Add Blazing blowpipe as fuzzy match for Toxic blowpipe (and vice versa)

### ISSUE THREAD

**Issue by fuzxi** [dillydill123/inventory-setups#240]
[Blazing blowpipe](https://oldschool.runescape.wiki/w/Blazing_blowpipe) is a [Toxic blowpipe](https://oldschool.runescape.wiki/w/Toxic_blowpipe) with a Leagues 4 ornament kit attached.

**Comment by dillydill123** [comment]
Done. Should be in
