### ISSUE TITLE
[Request]: Search notes in panel to find setups it is in

### ISSUE THREAD

**Issue by Intecpsp** [dillydill123/inventory-setups#242]
In a similar vein to #235, can a `notes:` tag be added to filter setups with specific text from the notes section?

Use Case: I recently obtained Augury and want to update some of my notes to utilize it instead of Mystic Might.

**Comment by dillydill123** [comment]
@rbbi  maybe you can tackle this one?

**Comment by dillydill123** [comment]
This is in now with 1.18
