### ISSUE TITLE
[Request]: Search Rune Pouch in panel to find setups it is in

### ISSUE THREAD

**Issue by Intecpsp** [dillydill123/inventory-setups#243]
In a similar vein to #235 and #242, can a `pouch:` tag be added to filter setups with specific runes in a pouch?

Use Case: `item:Rune-Pouch pouch:Cosmic-Rune` to help filter setups where a Rune Pouch is being utilized and it contains runes for Thralls.

**Comment by dillydill123** [comment]
`item:Cosmic-Rune` already checks in the rune pouch. It will also check inventory I guess. Is this is not sufficient for your use case?

**Comment by Intecpsp** [comment]
That works for me!
