### ISSUE TITLE
Setup sections are in reverse order when adding a setup to section(s)

### ISSUE THREAD

**Issue by Nightfirecat** [dillydill123/inventory-setups#246]
Similar to #215; my sections are, from top to bottom:

1. Slayer
2. Raids
3. Other PVM

![Screenshot_20240326_194619](https://github.com/dillydill123/inventory-setups/assets/2199511/e12a3f51-0c26-4a8c-866a-ff0827a26c2c)

**Comment by dillydill123** [comment]
That displays them in alphabetical order, which just happens to be opposite of the order tour sections are in. Double check by adding a few more test sections

**Comment by Nightfirecat** [comment]
Ah ok, if it's expected behavior then this can be closed.
