### ISSUE TITLE
[Suggestion] Dizana's quiver

### ISSUE THREAD

**Issue by SAwesome1018** [dillydill123/inventory-setups#249]
Would it be possible to have a second ammo slot added when Dizana's quiver is equipped/in the inventory, somewhat similar to how the run pouch works?

**Comment by dillydill123** [comment]
I'm planning on adding this. Might need some help testing it, so if anyone knows how to debug plugins and has a quiver it would be very helpful!

**Comment by SAwesome1018** [comment]
i dont know how to debug plugins, but i have a quiver and would be glad to help if its something that can be taught

**Comment by dillydill123** [comment]
If you have some programming experience and are willing to download the required software (Java, IntelliJ) then you should be able to help! I have the feature implemented and now just need to test.

**Comment by SAwesome1018** [comment]
i have both, what would be the best way to contact you for a walkthrough on how to get it fully setup?

**Comment by dillydill123** [comment]
First before you do anything, open RuneLite and make a copy of your current profile and select and test on that profile so you don't have to worry about messing up your existing data.

Rough guide:

1. Clone the repo
2. Open with IntelliJ - https://github.com/runelite/runelite/wiki/Building-with-IntelliJ-IDEA See this for some setup.
3. Checkout `quiver` git branch which has the feature implemented
4. Build and run - you need to do some additional work if you have a jagex account. https://github.com/runelite/runelite/wiki/Using-Jagex-Accounts
5. Log in to runelite and create a setup with a quiver. Existing setups should just have whatever is in your quiver now. 

I can message you on discord if you get stuck

**Comment by SAwesome1018** [comment]
discord would help, mine is the same as this username

**Comment by SAwesome1018** [comment]
if you could contact me on discord, it would help immensely. my username is sawesome1018
i was able to get runelite built, but i am struggling with adding the plugin to the project
