### ISSUE TITLE
Bank filter incorrect

### ISSUE THREAD

**Issue by YvesW** [dillydill123/inventory-setups#254]
Don't look at the setup, because it's crap, but bank filtering seems to be incorrect. I do not have any tag tabs called e.g. ``kalphite soldiers`` or ``kalphite``.

![image](https://github.com/dillydill123/inventory-setups/assets/7929021/04bd763b-c3da-466f-ba19-67224a13bf41)

As can be seen, the ``karamja gloves 4`` are missing in this case. They are definitely in my bank though.

![image](https://github.com/dillydill123/inventory-setups/assets/7929021/e7793ddf-0cd5-4e84-9204-31bd81b6e2cb)

**Comment by dillydill123** [comment]
Does fuzzy work here? Also did you add that slot to your setup via the search mechanism? The achievement diary items have weird behavior with the item search

**Comment by YvesW** [comment]
Fuzzy does not work. I've made the setup ages ago, so I'm not sure how I've added them. For good measure I just withdrew the item from the bank and used the ``Update Slot from Inventory`` option. It's still not showing up.

For other setups, it's screwing up the order and removing an item, it seems? 1 Bracelet of slaughter is missing. The gloves are at a different place, so are the cballs.

![image](https://github.com/dillydill123/inventory-setups/assets/7929021/5b03d72f-cda6-4968-8bf1-c936613a38b3)

Again, the setup itself is crap (not efficient). Could I have changed the setup in the bank at some point (thinking it was a tag tab instead of a filter from inventory setups), which causes this issue? I'm not sure how BTL and IS interact.

**Comment by dillydill123** [comment]
Bank tag layouts saves only the name and positions of items. It doesn't change order if the setup changes, so that's probably why. I'll take a look into the gloves and why they aren't appearing in the filter. For good measure try disabling bank tag layouts and check that they still don't appear.

**Comment by YvesW** [comment]
Ah. That explains most of it. It made sense for me that the layout would change if I changed it in inventory setups, since it was only a layout that existed when I had the filter option enabled. If that's how it's supposed to work then so be it.
Your comment did make me take another look at the item order, which made me notice that the gloves were way lower in the tag tab... Apologies.

Thus, the only potential issue would be having one bracelet too little in this setup. I am not sure if that's also expected behaviour though, if you modify either the setup or the layout later on. https://github.com/dillydill123/inventory-setups/issues/254#issuecomment-2125975089

**Comment by dillydill123** [comment]
Inventory setups doesn't do any bank layout at all, just filtering. So the missing bracelet would be due to BTL. You can reset the BTL layout with the white arrows in the bottom right I believe.

**Comment by YvesW** [comment]
Interesting that it doesn't automatically pick that up from inventory setups. My apologies then, it was all a BTL issue if it was an issue at all. I expected more of the funtionality to be part of inventory setups, but it's not.
