### ISSUE TITLE
Integration with Bank Tag Layouts broken in latest update

### ISSUE THREAD

**Issue by cporth9** [dillydill123/inventory-setups#257]
The functionality that allowed inventory setups to be sorted similar to bank tag layouts not longer works as of today.
![image](https://github.com/dillydill123/inventory-setups/assets/78776051/b40a9cfc-d28a-4482-880a-c68f3e12d8d0)

Also, when i right click certain items, it show options for different items in the layout.  left clicking to withdraw does not work sometimes
![image](https://github.com/dillydill123/inventory-setups/assets/78776051/45b93580-41e6-450b-a1eb-2924d9b7a371)

**Comment by dillydill123** [comment]
Did you restart your client? This was recently fixed https://github.com/dillydill123/inventory-setups/issues/256

**Comment by cporth9** [comment]
Yes just restarted my client thanks
