### ISSUE TITLE
Arrows in quiver are stuck in the first available bank slot

### ISSUE THREAD

**Issue by FelixJochems** [dillydill123/inventory-setups#261]
When using a quiver with arrows in it, the arrows will always default to the first available bank slot in said setup. You cannot move or drag it. The only way to have it not be in the first slot is to have items preceding it.

**Comment by dillydill123** [comment]
Can you provide a screenshot of this? This might change when inventory setups switches to core bank tags.

**Comment by FelixJochems** [comment]
Its not really that clearly visible on a screenshot so made a short video for you:

https://github.com/user-attachments/assets/9b15cca1-123a-4e29-87df-9cad840168e4

Yeah I've seen your ongoing effort to switch to core bank tags, they would be massive for situations as you can already see in the video above. I would honestly just focus on that first, especially if this specific bug might get fixed while converting to core bank tags. I'll keep the bug report open just for now and to have the info open.

Thank you for your work towards this amazing plugin so far!

**Comment by dillydill123** [comment]
The Core BTL update is live, could you check if this issue is resolved?

**Comment by IsaacGraham** [comment]
It does appear to be resolved - I had the same issue before and worked around it by adding the arrows as additional filtered items, but the workaround is not needed now.
