### ISSUE TITLE
Bank Filtering not working

### ISSUE THREAD

**Issue by Merkaba** [dillydill123/inventory-setups#264]
After a recent update, when I attempt to filter my bank with an inventory setup, the filter does not work. Bank UI remains unchanged but the side panel opens correctly.
![image](https://github.com/user-attachments/assets/d1b4cf85-904d-4fef-83a9-3c7b9383b1f8)

**Comment by dillydill123** [comment]
Is filtering enabled on the setup in the side panel?

**Comment by o-adge** [comment]
I am having the same issue, with default plugin settings. Old setups made years ago function correctly, but any newly created setups do not filter the bank as described by Merkaba above.

**Comment by dillydill123** [comment]
This should be fixed now, was due to the game update

**Comment by o-adge** [comment]
All good now, thanks!
