### ISSUE TITLE
If your not on the "Main/1st Tab" and click "Note" it stops the filtering

### ISSUE THREAD

**Issue by Simpuhl** [dillydill123/inventory-setups#265]
Probably already known but basically if your on another tab other than the first one, and then open your bank and click note it messes up the filtering.

**Comment by dillydill123** [comment]
This should be gone now with the layout update. Although if i'm going to re-add the old filtering it may appear again. Will leave this open for now.

**Comment by dillydill123** [comment]
Should be fix. Reopen if not
