### ISSUE TITLE
[Request] Add Blood Torva to Torva fuzzy match

### ISSUE THREAD

**Issue by WhatTheHai** [dillydill123/inventory-setups#268]
Unsure if it works the other way around, but when toggling fuzzy on Torva it doesn't pick up on Blood Torva

**Comment by dillydill123** [comment]
Hello, is this still a problem with the most recent update?

**Comment by WhatTheHai** [comment]
> Hello, is this still a problem with the most recent update?

Heya, I can confirm this is still the case with the current version

**Comment by dillydill123** [comment]
I added mapping to the latest update. Try again please

**Comment by WhatTheHai** [comment]
Works for me now, thank you for the quick fix! I've only tested it with torva platebody as I do not have any other normal Torva pieces, but I assume the rest would work fine
