### ISSUE TITLE
Possible to treat all charged jewelry as the same item?

### ISSUE THREAD

**Issue by jacksonbob10199** [dillydill123/inventory-setups#27]
Right now if I create a setup with an amulet of glory(3), it will show any other charged variation, for example an amulet of glory(2), as being a different item (highlighted red and more importantly won't show up in the bank filter). It would be nice if those two were treated as the same item so that all the charged amulet of glories in bank showed up in the filter.

**Comment by dillydill123** [comment]
Turn off Variation Difference:

![image](https://user-images.githubusercontent.com/15637422/80175062-8af9d580-85c2-11ea-9b1c-36e299fec8c4.png)

This will cause items that are similar (like jewelry with different charges) as the same.

**Comment by jacksonbob10199** [comment]
Thanks
