### ISSUE TITLE
Varlamore Graceful Doesn't Appear in Bank Filter

### ISSUE THREAD

**Issue by abanksss** [dillydill123/inventory-setups#273]
I just tried to update my graceful in my setups to the new varlamore graceful but it doesn't show up in the bank filter.

**Comment by dillydill123** [comment]
Is this fixed? If not I think it should be soon

**Comment by dillydill123** [comment]
This should be fixed now. Can you confirm?

**Comment by TekkadanPlays** [comment]
This appears to be fixed for me. Was having the same issue.
