### ISSUE TITLE
Draw over Intentory

### ISSUE THREAD

**Issue by qnps** [dillydill123/inventory-setups#28]
I think it would be cool if there's an option to show the inventory items drawn over the inventory to make it easier to organize.

https://i.imgur.com/KfQMUR3.png

**Comment by dillydill123** [comment]
I like it, but I'm not sure on the exact details. 

- Should this show up only in the bank? Or all the time? I think it may be annoying if it was on all the time (if your in the middle of a trip)
- Should it be toggle-able for all setups separately? Or an off-on for all setups?

I think this could be taken even further and the correct slot could be "highlighted" in some way. 

I've never dealt with overlays but I might be interested in implementing this. I need to figure out the exact details of how it should behave though.

**Comment by dillydill123** [comment]
No plans to implement this.
