### ISSUE TITLE
Inventory Setups Bank Filter Persisting Despite Lack of Active Panel

### ISSUE THREAD

**Issue by reaganrandolph1015** [dillydill123/inventory-setups#282]
Bank filtering persists despite "Require Active Panel for Filtering" setting being enabled and Inventory Setup panel not being open. Issue began after latest update. Also, shows a bugged label on top of the bank UI. 

![Err](https://github.com/user-attachments/assets/b3afec26-3c96-4314-8ed3-c748b5fbdad6)

**Comment by dillydill123** [comment]
Could you provide some reproducible steps for this?

**Comment by dillydill123** [comment]
I found the issue and made a change to it.

**Comment by reaganrandolph1015** [comment]
Still experiencing the issue after closing and reopening Runelite. 

Steps: Open an Inventory Setup, open bank(works as should), close bank, switch runelite tab/panel, open bank and Inventory Setup layout still persists

**Comment by dillydill123** [comment]
Sorry, i wasn't clear. This will be in the next update. You'll see a patch notes panel when it's leave. I was just acknowledging that I tweaked the behavior to fix it.

**Comment by reaganrandolph1015** [comment]
Ahh okay thank you very much :)

**Comment by dillydill123** [comment]
Merged the update. Please create a new issue if there are still problems
