### ISSUE TITLE
Add icon to bank tag layout

### ISSUE THREAD

**Issue by dovry** [dillydill123/inventory-setups#283]
The ItemID after the tag name is the icon that is displayed, and defaults to Spade with ID 952

Is it feasible to include the icon from Setups in the import string ?

**Comment by dillydill123** [comment]
It actually is using this, but by default inventory setups does not save an icon Id unless you specifically set it. It just defaults to the weapon. So I've done the same for the bank tag export. So, if you have a specific icon Id you set, it will choose that. If not, it will choose the weapon of the setup. If not that, it will choose a spade. Thanks for reporting

**Comment by dillydill123** [comment]
Released in 1.20.1
