### ISSUE TITLE
Way to disable new layout in the bank? 

### ISSUE THREAD

**Issue by mber215** [dillydill123/inventory-setups#284]
When selecting a setup, the new update arranges the items differently than it used to - is there a way to revert to the old method?

**Comment by Simpuhl** [comment]
I just made this post, is it the same as your issue? https://github.com/dillydill123/inventory-setups/issues/286

I added screenshots so it makes sense

**Comment by salehmdev** [comment]
@Simpuhl - Yes, although your post contains more helpful details. It's exactly why I thumb'd this issue.

**Comment by dillydill123** [comment]
The new layout system is completely customizable. You can drag and move the items in the layout without affecting the actual positions of items in your bank. The layout info is saved.

There’s no way to revert to the old method as of now.

**Comment by Simpuhl** [comment]
> The new layout system is completely customizable. You can drag and move the items in the layout without affecting the actual positions of items in your bank. You can duplicate or remove duplicate items as well. The layout info is saved for each setup.
> 
> There’s no way to revert to the old method as of now.

I am heart broken :(

Do you have plans to allow for the old layout? A simple toggle would be amazing

**Comment by dillydill123** [comment]
I could look into adding it, but I’m curious what’s lacking about the new system? Could you tell me why you would prefer the old system? As I said before, you can customize the layout entirely with the new system.

**Comment by JZomDev** [comment]
> I could look into adding it, but I’m curious what’s lacking about the new system? Could you tell me why you would prefer the old system? As I said before, you can customize the layout entirely with the new system.

They seem to have used the inventory set ups plugin without the layouts, they just wanted the inventory set up plugin to highlight when missing items and load a tag tab without the layout applied - which is what the plugin used to do on its own without BTL or bank tag's layout applied.

**Comment by mber215** [comment]
> I could look into adding it, but I’m curious what’s lacking about the new system? Could you tell me why you would prefer the old system? As I said before, you can customize the layout entirely with the new system.

For me, it's just because of being accustomed to it and I've rearranged my bank in a way that makes withdrawing everything quickly after it filtered. Having everything in a row rather than arranged in an inventory feels faster to me. 

Just my 2 cents, and I'm sure others may disagree but if it's easy to add a toggle in the settings for it, that would be wonderful.

**Comment by dillydill123** [comment]
There is a zigzag option you can select for the preset which puts items in a row. And as I said you can move the items in any configuration you wish without affecting actual bank item positions.

As for the toggle. I can look into it but it may depend on Bank Tags since it’s doing the heavy lifting now.

**Comment by Simpuhl** [comment]
> I could look into adding it, but I’m curious what’s lacking about the new system? Could you tell me why you would prefer the old system? As I said before, you can customize the layout entirely with the new system.

Might be workable if you added that disable duplicates option but for now my brain is hating this new layout. I never liked it in the past either which is why I always stuck to the old layout.

**Comment by salehmdev** [comment]
@dillydill123 Yea - I was going to add that the old way behaved exactly like a Bank Tag would, with the added benefit of highlighting on the right

**Comment by Simpuhl** [comment]
> Okay, seems there is enough support for this and since Bank Tags has this toggle it’s probably possible then. I’ll investigate.

You can probably merge this with the incident I created also: https://github.com/dillydill123/inventory-setups/issues/286

**Comment by wanieru** [comment]
I just wanted to add that I absolutely prefer the new auto-layout, and that I used Bank Tag Layouts to generate them before. Excited about the possibility to have them natively with Inventory Setups. However, now, if I change/add equipment or items after the intial layout has been generated, the new items don't get added to the correct spots.
For example, changing the the helmet slot in this layout, results in this:
![image](https://github.com/user-attachments/assets/bd86e769-3a1f-476d-965a-7ccf69ff1639)
 
![image](https://github.com/user-attachments/assets/8718dfc9-029a-451d-88b5-ac39317768b8)


When using Bank Tag Layouts, I could always just click this button to regenerate the layout and get everything back to where they're supposed to be, but that button doesn't appear on the layouts anymore.
![image](https://github.com/user-attachments/assets/82ab6141-0e42-4893-b194-51e3e9cdc717)


To be honest, I'm having a bit of a hard time keeping track of which plugins are providing which functionality, so excuse me if I got some of that wrong.

**Comment by Sokywocky** [comment]
It's a very frustrating update, the old system was so much nicer and I don't see the problem with having the option to revert to it, it's way more annoying trying to gear up rapidly and my presets are filled with items not even in my preset. Please please please revert this change.
![2cbc379086a311d8bb78cbb9ead0c7e4](https://github.com/user-attachments/assets/650550d0-373e-4eb4-b925-cdfc5e8ff5bf)
![8c8548aae02a88ffbac4ebcf6a0e715d](https://github.com/user-attachments/assets/4762c3d5-318a-4e13-be77-c209a2b2894b)

**Comment by dillydill123** [comment]
@Sokywocky that looks like a bug. Could you create a new issue for that?

**Comment by dillydill123** [comment]
There is now a new toggle in the settings that will globally enable or disable layouts. This will bring back the old filtering style for all setups.

![image](https://github.com/user-attachments/assets/2afc3b01-1f5c-4cb3-bb96-f27cb659b7e2)

Please make a new issue for any new problems

**Comment by joshfaber95** [comment]
Do you know why the refresh button to update the layout to reflect inventory setup changes is gone? You can see that it still shows in when you're just looking at a bank tag tab.

![Screenshot 2024-11-08 150202](https://github.com/user-attachments/assets/8b5d5424-7f09-464c-87e0-abc05e690d17)

However, when you have an inventory setup selected, it doesn't show it and there's no way to quickly update your layout to match changes made in the inventory setup.

![Screenshot 2024-11-08 150223](https://github.com/user-attachments/assets/46195870-1de3-4454-8354-20f2817be476)

**Comment by dillydill123** [comment]
@joshfaber95 that was from bank tags layouts. The option to reset the layout is in the right click menu of “Show worn items” now.

please make a new issue for problems in the future

**Comment by joshfaber95** [comment]
@dillydill123 Got it sorry, I guess I misunderstood this issue, I thought it was related. Thanks!
