### ISSUE TITLE
Option "1. Keep" when toggling zig-zag or preset layout fails with keyboard option 1

### ISSUE THREAD

**Issue by TekkadanPlays** [dillydill123/inventory-setups#285]
When selecting either "zig-zag" or "preset" options from the menu, the interface dialogue shown below does not correctly register the first option "keep" **when pressing 1 on the keyboard**. If clicked it does work however.

This problem persists whether zig-zag or preset is selected.

![image](https://github.com/user-attachments/assets/88e9e221-e14f-48f9-be73-dc6f7a972db6)

**Comment by dillydill123** [comment]
Thanks for reporting. I found the bug and will fix.
