### ISSUE TITLE
Enable Old Layout? New Layout is forced?

### ISSUE THREAD

**Issue by Simpuhl** [dillydill123/inventory-setups#286]
After today's update, it looks like the new layout is forced with no way to disable it.

Prior to today's update, my inventory setup filters always looked like these: (found online)
![image](https://github.com/user-attachments/assets/6e1333c7-cd90-4c57-af6a-44568b20e305)

![image](https://github.com/user-attachments/assets/ec93014e-19fb-4bd8-8835-99c068acae33)

But now I am forced to use this with no way to disable it:
![image](https://github.com/user-attachments/assets/6f7aed2d-4c99-4594-aa19-173683c24907)

**Comment by dillydill123** [comment]
Duplicate of https://github.com/dillydill123/inventory-setups/issues/284. Closing this one

**Comment by Simpuhl** [comment]
Thank you
