### ISSUE TITLE
Excessive Scrollbar Issues

### ISSUE THREAD

**Issue by verafeiyd** [dillydill123/inventory-setups#287]
For some reason with this new update, it adds an excess of extra space underneath the usual equipment put into a loadout. This also makes it so sometimes when re-opening the bank, you end up half scrolled down the setup screen even though there is 0 item to add that space. A hotfix would be much appreciated
![image](https://github.com/user-attachments/assets/d2483640-0aa9-4b50-af86-92b8f48e8fdd)

**Comment by dillydill123** [comment]
Can you check if this is an issue with bank tags tag tabs? It may be something that needs fixing on that end.

**Comment by TekkadanPlays** [comment]
To add to this issue, it seems that the 'remembered scroll position' is affecting the position of presets' scroll position also.

For example, if you scroll down a bit on the "all tabs" section of bank, the scroll position will be recalled by the preset as well:

To recreate, scroll down some and exit the bank interface:

![image](https://github.com/user-attachments/assets/016456a9-d99f-49b6-99ee-6aa693b60bac)

Then open a preset with the plugin and access the bank:

![image](https://github.com/user-attachments/assets/b60c7668-afd2-45bb-8342-01f131ef8355)

Of course the preset is loading correctly, but the scroll position is being recalled:

![image](https://github.com/user-attachments/assets/371c657d-4aed-4951-881a-afc16b2535ff)

**Comment by dillydill123** [comment]
I mean to say, does this also happen in Bank Tags Tag Tabs when layouts are activated? does it have a huge scroll bar?

**Comment by dillydill123** [comment]
I spoke with Adam, who gave me the response that "this is intentional atm so you can move things lower in the layout. it does it for any layout". So if you'd like to have it changed you should make an issue in Core Runelite

**Comment by dillydill123** [comment]
Although I am able to reset the scroll bar position to the top when opening the bank. This fixes the issue but also makes it so the scroll bar position in the bank is never saved if you have a setup open with layouts.

For example, if you open a setup and scroll down, then exit the bank, then reenter, the scroll bar will be set to the top again. Is this an acceptable situation?

**Comment by TekkadanPlays** [comment]
Sounds like it could be a matter of preference. I lean toward preferring my scroll to reset to the top, personally. I have always liked that my bank remembers my scroll position _except_ when I choose to view a preset. None of my presets require scrolling at this time. With the new update, that may change, but only for a small sample size.

**Comment by escro** [comment]
> I mean to say, does this also happen in Bank Tags Tag Tabs when layouts are activated? does it have a huge scroll bar?

I would like to add that I have bank tags active, and the scroll bar is normal. This is how the loadout used to appear for inventory setups before the last update, but now the scroll bar is stretched out by default. 
Would it be possible to change it back? If I need to make more space I would prefer to do it manually by dragging items to the bottom rather than have it extended by default.
![image](https://github.com/user-attachments/assets/b03c7f4e-ce7b-48d7-bb5f-5dc82c7a6cfb)

**Comment by dillydill123** [comment]
@escro That's the hub plugin bank tag layouts, not core Bank Tags. The hub plugin Bank Tag Layouts has this behavior, not regular bank tags. Regular bank tags also supports layouts by the way, along with potion storage. hub Bank Tag layouts does not support potion storage.

Anyways, I pushed an update that makes it so the scrollbar is reset to the top. Please create new issues if you find any other issues with this.
