### ISSUE TITLE
[Suggestion] Toggle Duplicate option

### ISSUE THREAD

**Issue by verafeiyd** [dillydill123/inventory-setups#288]
Upon creation of a new setup, it copies the inventory 1:1. While I understand this is the way the plugin has worked for quite a while, I want to suggest a option to disable the creation of duplicates upon making a new setup. I personally, as I know quite a few players do, end up having to remove all the duplicates from their setups because they simply dont need the clutter/15 different manta rays to click when menu entry swapper works for withdrawing and depositing in preset quantities.

Either make a remove all but 1 option, or a plugin setting to prevent duplicates, and the playerbase will be much happier.

![image](https://github.com/user-attachments/assets/56f274a7-3035-4945-8c8d-55471b60bc11)

**Comment by dillydill123** [comment]
I can make a plugin setting to disable duplicates when creating the layout.

**Comment by verafeiyd** [comment]
incredible, thank you so unbelievably much. ive had to remove duplicates like this for over 40 setups at this point and honestly i shouldve asked years ago. 10/10

**Comment by Simpuhl** [comment]
> I can make a plugin setting to disable duplicates when creating the layout.

That would be great until we can find a way to disable the forced new layout

**Comment by escro** [comment]
I believe this didn't use to be a problem if you used the bank tag layouts plugin alongside inventory setups, as there is an option to limit or disable duplicates in the layout. 
![image](https://github.com/user-attachments/assets/124068e0-09ab-4868-aa35-ab9995aa47a6)
Here you can see I have it set to max 2, but since the update to inventory setups it doesn't seem to work anymore.
In any case, it would be very much appreciated if you could add a "disable duplicates" or a "duplicate limit" setting to inventory setups.

**Comment by tknoeny** [comment]
+1 on being able to revert back to old layout, all of my setups have been changed. This looks clunky where before everything was just shown as if a regular filter was applied. There's also so much blank space now for some reason.
![image](https://github.com/user-attachments/assets/eb358355-3941-4787-89e4-2fcbc5f6838f)
![image](https://github.com/user-attachments/assets/ae466d7e-b155-4f53-baef-df114666898b)

**Comment by dillydill123** [comment]
There are new options to disable duplicates and disable layouts
![image](https://github.com/user-attachments/assets/6416e290-22a6-4ef2-97af-025e3b776810)

Please create a new issue if you have any other problems or suggestions

**Comment by rudes** [comment]
@dillydill123 would it be possible to expand this to just pots/food? 
For example i might want a backup slaughter bracelet in my inventory and if i do that, i have to manually make a dupe and then reorder my entire setup in zig zag to put it in the right order, or i have to delete 10 dupes of an angler to get the one dupe bracelet.
