### ISSUE TITLE
"Filter All" option missing

### ISSUE THREAD

**Issue by IsaacGraham** [dillydill123/inventory-setups#289]
Please let me know if this is the wrong plugin to report on.

I have until today been able to use a Filter All option in the top-left button of the bank interface to return to my inventory setup layout after navigating to a bank tab instead. I can't see if there's been another button added to do this, as the only other ways I know of to get back to the setup are to reopen the bank or close and reopen the setup.

**Comment by dillydill123** [comment]
You can use a hot key in the settings but I realize now I should add a menu option enable the refilter when you have a setup selected. I'll do that.

**Comment by SilleeCookie** [comment]
> You can use a hot key in the settings but I realize now I should add a menu option enable the refilter when you have a setup selected. I'll do that.

came to report this as well, the filter hotkey function doesnt work for me, not sure why but have tried many combinations

**Comment by dillydill123** [comment]
@SilleeCookie Do you have bank filtering enabled for the setup? The filter icon in the left side should be white to indicate you want filtering for that setup.

![image](https://github.com/user-attachments/assets/82800218-345e-4914-9277-40dbb80c2034)

**Comment by dillydill123** [comment]
"Filter Bank" Menu entry has been added in the most recent update. Please make a new issue for any other outstanding problems

**Comment by SilleeCookie** [comment]
> @SilleeCookie Do you have bank filtering enabled for the setup? The filter icon in the left side should be white to indicate you want filtering for that setup. I'm unable to reproduce your issue.
> 
> ![image](https://private-user-images.githubusercontent.com/15637422/384259204-82800218-345e-4914-9277-40dbb80c2034.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwODkyNDQsIm5iZiI6MTczMTA4ODk0NCwicGF0aCI6Ii8xNTYzNzQyMi8zODQyNTkyMDQtODI4MDAyMTgtMzQ1ZS00OTE0LTkyNzctNDBkYmI4MGMyMDM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDE4MDIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5ZTdkNzNkMTYwMTI1MjhjMjliMjI5ZWVjYzllMTk0ODJjMzc4NTJiMDQ5MTNjOGUyMGYzZmRhM2Q4ZjkxNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fbQnVrX2sXloXkUUotjzw_Sxuf9L7QOje05NSd-rFH8)

yes indeed, i figured it out about 10 minutes ago, apparently my hotkey presses work on my keyboard but may be too fast for the plugin to detect it when i map to one of my mmo mouse keys (how i prefer), if i hold it a half second longer it works. Also had to remove combo inputs like ctrl+1 for the same reason on my keyboard.
