### ISSUE TITLE
Bug: Switching Withdraw from Items to Notes Cancels Filtering

### ISSUE THREAD

**Issue by dereklopes** [dillydill123/inventory-setups#29]
With an inventory setup selected and bank filtering enabled, switching the withdraw type from items to notes will cancel the filtering and put you back into your regular bank.

This is really inconvenient when noted items are part of an inventory setup. To get around this you have to deselect the inventory setup, switch the withdraw type, then reselect the setup. It seems to happen almost every time, and switching from notes to items does not behave the same way.

**Comment by dillydill123** [comment]
Hey, thanks for making the issue. Unfortunately there's not much I can do for this. Take a look here: https://github.com/dillydill123/inventory-setups/issues/22. Basically you have to turn off the bank tags plugin in order for this to stop happening

**Comment by dereklopes** [comment]
Oh sorry about that, I probably should have looked at the closed issues. Thanks for the suggestion!
