### ISSUE TITLE
Issue moving items around in layout

### ISSUE THREAD

**Issue by acdyer** [dillydill123/inventory-setups#292]
Since the update today I can't freely move items around in the bank layout. When I try to swap two items with each other, it inserts it instead, shifting everything else in the row, and sometimes even shifting things back to the row above. I don't see anything in the settings that changes or addresses this.

**Comment by dillydill123** [comment]
Is the filtering working? Each setup must be set to use filtering.
Do you have “Use Layouts” set in the settings?

**Comment by acdyer** [comment]
Yes to both of those questions. It's correctly filtering, but then if I go in to try and manually move something, it doesn't work well.

**Comment by dillydill123** [comment]
Can you send a gift? Do you have bank tags on?

**Comment by acdyer** [comment]
Not sure how to upload a gif, but here are a couple screenshots. First image is how it looks at the start, and second is how it looks after I drag the torva platebody on top of the masori chaps. Which should just swap them and leave everything else in place, but now it inserts it in the row and shifts everything over.

I have both bank tags and bank tab layouts enabled.

https://imgur.com/a/qtqShLX

**Comment by acdyer** [comment]
Ok, sorry I'm an idiot. Somehow my bank was set to insert instead of swap. Not sure how since I've never used insert in the years I've played this game. Sorry for wasting your time lol.

**Comment by dillydill123** [comment]
No problem. At least I’m aware of this if it occurs again with someone else.
