### ISSUE TITLE
Bring back the layout button (🔀) within the bank interface

### ISSUE THREAD

**Issue by Infinitay** [dillydill123/inventory-setups#299]
![image](https://github.com/user-attachments/assets/aaa4cbd4-e3e9-4b73-80c2-0f31b478ea39)

Would it be possible to get this button back? I know we can right click for the sub-menu to enable auto-layout, but this button allowed us to preview the autolayout before confirming it. This saved me many times in the past where if I used auto-layout it would shift over all my items, and I could cancel the auto layout changes. However, I'm not sure if the sub-menu has this feature, so I have yet to bother to use it on setups which I moved items around in my layout.

**Comment by dillydill123** [comment]
I will not be adding that button back. The auto layout button in the show worn items sub menu will show a preview and let you save or undo the layout just like that button does.

**Comment by Infinitay** [comment]
Thanks for letting me know. I'll use that instead now.
