### ISSUE TITLE
Add rune pouch runes under inventory

### ISSUE THREAD

**Issue by ConradicalMel** [dillydill123/inventory-setups#3]
![runelite_inventory_setup](https://user-images.githubusercontent.com/32449783/71701421-4ccc7200-2d97-11ea-97e2-721336fc4f16.png)

**Comment by dillydill123** [comment]
Runes and their amounts in the rune pouch. can be accessed through varbits

from Varbits.java:

RUNE_POUCH_RUNE1(29),
RUNE_POUCH_RUNE2(1622),	
RUNE_POUCH_RUNE3(1623),
RUNE_POUCH_AMOUNT1(1624),
RUNE_POUCH_AMOUNT2(1625),
RUNE_POUCH_AMOUNT3(1626),

I think order should not be considered for the highlighting purposes. Just check if the runes in the setup are in the pouch one by one.

If the setup contains a rune pouch with an empty space, should the space be highlighted if the player's runepouch doesn't contain the empty space? I'm thinking yes for now.

**Comment by asherbasher** [comment]
> I think order should not be considered for the highlighting purposes. Just check if the runes in the setup are in the pouch one by one.

I agree, I can't think of a situation where the order would ever be relevant.

> If the setup contains a rune pouch with an empty space, should the space be highlighted if the player's runepouch doesn't contain the empty space? I'm thinking yes for now.

I would say yes also, since the spot may have been purposely left open in anticipation for dropped runes to go there. The user can easily just update the setup if they no longer want it to have an empty space too.
