### ISSUE TITLE
 Remove Tagging Option from Deposit items

### ISSUE THREAD

**Issue by verafeiyd** [dillydill123/inventory-setups#300]
![image](https://github.com/user-attachments/assets/99279f25-d834-4683-a885-db3ddf9577d6)
so, this only happens with inventory setups enabled, but personally, I don't use tags *whatsoever*. This may be due to not really understanding them, but its leading me to want for the removal of this option. /gz

**Comment by dillydill123** [comment]
This requires a change in RuneLite that hasn’t been released yet. Adam is aware and working on it

**Comment by dillydill123** [comment]
This should be gone now
