### ISSUE TITLE
Feature Request: Add Spellbook to Inventory Setups

### ISSUE THREAD

**Issue by Marstead** [dillydill123/inventory-setups#31]
It would be useful to include the current spellbook when snapshotting an Inventory Setup, and to highlight an invalid Spellbook if error highlighting is enabled.

Two mockups for where the icon could go:

Mockup #1: 
![image](https://user-images.githubusercontent.com/54672873/81627155-679c9c00-93b2-11ea-8521-0e2a6831058d.png)

Mockup #2: 
![image](https://user-images.githubusercontent.com/54672873/81627145-623f5180-93b2-11ea-98c7-62e678f3aa45.png)

**Comment by dillydill123** [comment]
Made good progress so far.

![image](https://user-images.githubusercontent.com/15637422/82267924-b78fdb80-993b-11ea-9a19-2d437e60f831.png)

Also added two menu entries to grab the current spellbook and to cycle between spellbooks so you can update a setup without having to manually change spellbooks in game.

**Comment by dillydill123** [comment]
![image](https://user-images.githubusercontent.com/15637422/82269339-6bdf3100-993f-11ea-9dd7-03c21b2c11c9.png)

I've decided to just add 4 menu entries to update the spellbook. I think this is less complicated.

**Comment by dillydill123** [comment]
It's available now in the plugin
