### ISSUE TITLE
Auto Layout

### ISSUE THREAD

**Issue by Devin345458** [dillydill123/inventory-setups#311]
<img width="1377" alt="image" src="https://github.com/user-attachments/assets/b278a390-1ea6-4496-bd80-5726a46498c4">
Issue with auto layout

**Comment by dillydill123** [comment]
What's the issue? Lack of duplicates? Do you have the "Add duplicates" option in the settings?

**Comment by Devin345458** [comment]
I figured it out. There was a message in the chat to confirm the new layout. Thank you.
