### ISSUE TITLE
Ability to detect when runes are in a rune pouch

### ISSUE THREAD

**Issue by JDansercoer** [dillydill123/inventory-setups#32]
Hey man, 

First of all, love the plugin! Really saves me from having to make bank tags for everything I do!

However, one more nice addition would be if the plugin was able to use a filled runepouch with the correct runes when deciding if a slot is correct or not.

![image](https://user-images.githubusercontent.com/11869830/82297502-09c01380-99b3-11ea-8ada-c9b179899d73.png)

In the screenshot above, you can see that my setup requires astrals, but since I just finished a raid, they're in my rune pouch. However, the plugin acts like my astrals are missing, when in fact they are not.

Is this something that is technically possible?

**Comment by dillydill123** [comment]
Technically possible, yes. But actually I think I prefer it this way. This is because you may not want to bring a rune pouch in some situations (e.g. wildy). So making it not highlight if you have a rune pouch instead of the actual rune can be misleading.

**Comment by JDansercoer** [comment]
Yes, certainly don't want this to be enabled by default, but was more thinking towards it being an option.

**Comment by dillydill123** [comment]
Ok, I can take a look further into this.

**Comment by dillydill123** [comment]
I'm reworking the variation differences and I'm thinking there may be a way to integrate this with the new update.

**Comment by dillydill123** [comment]
So I know I have not put any priority in this issue. Sorry about that!  But now that variations differences has been turned into slot specific fuzzy, perhaps I can make it so runes that are labeled fuzzy can be substituted with the runepouch with the correct runes. I think I may be able to do this for unordered highlighting as well. I think I still want a configuration option so it's more of an opt-in feature. Therefore you would need to set the slot as fuzzy and have the config enabled. What do you think?
