### ISSUE TITLE
Option to only highlight stack differences that are lower

### ISSUE THREAD

**Issue by JDansercoer** [dillydill123/inventory-setups#33]
Would it be possible to add an option to the stack differences highlighter so that it only highlights if the stack is lower?

The screenshot below would then correctly highlight, since 2 water runes is less than the required 3

![image](https://user-images.githubusercontent.com/11869830/82297889-9a96ef00-99b3-11ea-9208-6c39ee51032e.png)

However, the next screenshot should not warrant a highlight, since the stack is higher than what is required in the setup

![image](https://user-images.githubusercontent.com/11869830/82297946-b0a4af80-99b3-11ea-829d-e195933f605a.png)

**Comment by dillydill123** [comment]
This gives me similar vibes as your other suggestion, in that it could be misleading if someone accidentally brings too many of an item and the setup doesn't highlight. But the stack option doesn't really have much use otherwise so I'm willing to update it. Perhaps a toggle in the config? This would make it so it's applied to all setups. At the moment I don't have much real estate to work with on the panels. So doing a setup specific option might be difficult.

**Comment by JDansercoer** [comment]
Not sure what the capabilities of the client are, but can't you make a three way toggle? That has three states, so that it can cycle "Don't warn about stacks", "Warn about stacks" and "Only warn about stacks that are too low"?

**Comment by dillydill123** [comment]
The three way toggle isn't a bad idea. Or maybe a right click menu. I'll think on this some more.

**Comment by bwhite94** [comment]
I came looking to see if someone proposed this exact option. For the toggle mentioned above you can still have this on the setup card. You could just re-use the same icon for stack differences, potentially adding a `<` symbol for the third state. For example the two icons followed by a third option similar to attached example below.
![Inventory Setups Example 1](https://user-images.githubusercontent.com/14366690/93162865-a6858a00-f6e3-11ea-81d5-173ee750e748.png)

I may fork and look into this in the soon future. @dillydill123, let me know if you'd be open to accepting a PR for this, if I do work it.

**Comment by dillydill123** [comment]
Hey, I apologize for my inactivity on this plugin. Yes, I'm willing to accept a PR. Here are development ideas to help you get started:

stackDifference in InventorySetup will become an enum instead of a boolean. Does this cause any problems when loading configs that still have a boolean stored (old configs)?

I would like to create a "cycle" button class that has more than one state. This would be a generic class that cycles between the different states of the button. This is so I don't have to duplicate the same logic in the future for other buttons that would behave similarly (sorting button). On click, it should be able to set the proper image and modify a state that can be read from other parts of the plugin. Perhaps it can be templated so any enum can be used with it to return the state.

If you have difficulty making the icon, just use a placeholder and I can make an icon. 

Let me know if you have any additional questions. I'll get back to working on this plugin soon!

**Comment by dillydill123** [comment]
I've added some code for a generic cycle button. I'll continue working on this feature.

**Comment by bwhite94** [comment]
Thanks for the update. Let me know if I can assist in any way!

**Comment by dillydill123** [comment]
I think it's almost done. Just need to do some more testing. This actually broke a few more things that I wasn't expecting, like the unordered highlighting (needed to be refactored a little), and more importantly the config that stores all setup data. Switching the stackDifference from a boolean to a Enum caused difficulty with serialization, so I've added some code that will fix the json before it gets serialized. 

![stackdiff](https://user-images.githubusercontent.com/15637422/94353914-2dbbf180-0044-11eb-9af9-86190e6b0aad.gif)

You can see that I also added a greater than option just for completion sake. I want to do some more testing and add some more features before I make a PR. In fact, do you think you can assist with testing? I mainly want to make sure the config stuff is all working properly. If you can, please make a new test profile or backup your old settings before testing! This is what I do to avoid losing my setups :)

**Comment by dillydill123** [comment]
I also fixed it so the rune pouch will now consider stack sizes

**Comment by bwhite94** [comment]
Sure, I will take some time later tonight to set up my environment and do a round of testing with pre-existing setups. I'll let you know what I find!

**Comment by bwhite94** [comment]
I'm sorry, this may be a dumb question, but what is the process for importing external runelite plugins for development testing? I thought it would be as simple as loading the source files into the runelite project. If you can provide any details, I can assist with testing.

**Comment by dillydill123** [comment]
Testing external plugins is actually pretty easy. Just clone this repo and run/debug the test class:

inventory-setups\src\test\java\inventorysetups\InventorySetupsPluginTest.java

Take a look here: https://github.com/runelite/plugin-hub

**Comment by bwhite94** [comment]
Thanks, I actually re-read that same entry and apparently I had skipped over that statement. Oops! 

I did some testing with a few of the profiles I had. I took a backup of the setups JSON and a few screenshots of the config in the prior version of the plugin. Both appear to be reflecting the same on load. Additionally, I noticed the boolean value for `stackDifference` in each setup config appears to only be converted to an ENUM when toggling through one of your setup selections. All of the values for each setup converted from boolean to ENUM correctly and no states were lost. 

I reverted a few times and tried a couple of different entry states for `stackDifference` values. All seemed well in every instance I could come up with.

### Prior version: 
![RuneLite_2020-09-27_20-39-33](https://user-images.githubusercontent.com/14366690/94380148-50144480-0102-11eb-94e7-dd05d3847355.png)

### Testing version on load:
![java_2020-09-27_20-40-25](https://user-images.githubusercontent.com/14366690/94380154-586c7f80-0102-11eb-8955-99bf25f8b128.png)

### Testing version after updating birdhouse runs stack difference (ENUM conversion):
![java_2020-09-27_20-52-48](https://user-images.githubusercontent.com/14366690/94380422-78e90980-0103-11eb-8608-cdbcd1da2c43.png)

### Additional testing on stack difference states are all pass.
![2020-09-27_21-01-06](https://user-images.githubusercontent.com/14366690/94380744-ddf12f00-0104-11eb-8ee7-69218fe0762c.gif)

**Comment by bwhite94** [comment]
> I also fixed it so the rune pouch will now consider stack sizes

I just noticed this comment from earlier. I unfortunately still haven't used the rune pouch on my accounts yet (noob, I know) so I can't test this aspect.

**Comment by dillydill123** [comment]
> Additionally, I noticed the boolean value for `stackDifference` in each setup config appears to only be converted to an ENUM when toggling through one of your setup selections. All of the values for each setup converted from boolean to ENUM correctly and no states were lost.

Yeah, the config only gets updated when something about any setup changes. So that makes sense. Glad to see that it's working :)

**Comment by dillydill123** [comment]
Added in 1.8, which is available now.
