### ISSUE TITLE
Suggestion: Add a notes section

### ISSUE THREAD

**Issue by oliviergermain** [dillydill123/inventory-setups#34]
Would it be possible to add a notes section? I know there is already a notes tab in RuneLite, but having to switch and store everything there is kind of annoying. 
I think it could be useful to store notes for specific activities with their respectives inventory setups.

For example, one could write his farm run.
![suggestion notes example](https://user-images.githubusercontent.com/53048482/82474815-9b09b580-9a99-11ea-9f59-1c881afec820.png)

**Comment by dillydill123** [comment]
I don't think there's a problem technically but are there any other use cases for this? I personally can't really think of anything I would want to use this for. And when I do farm runs I use the Time Tracking plugin to give me the list of patches.

I'm not saying it's a bad idea, just questioning how useful it is.

**Comment by oliviergermain** [comment]
One could write down some notes about location, prayers or gear alternatives for slayer tasks or pvm.
I'm mostly thinking notes section is interesting for people that don't have alot of knowledge about everything and need to wiki very often.

**Comment by dillydill123** [comment]
Ok, I don't see any harm in adding this, except making the config slightly larger, but that's no big deal. I think I will add an option to hide it in the config as well.

**Comment by dillydill123** [comment]
![O243xNqN8o](https://user-images.githubusercontent.com/15637422/87862539-49f23280-c91f-11ea-88cc-14fe039ea4f1.gif)

Made some progress on this. For some reason I can't get the note box to have more height. But it does expand with the page.

**Comment by dillydill123** [comment]
Notes feature has been added to 1.7 and is available now. Fixed the expanding issue as well.

**Comment by zachariah25** [comment]
This is seriously awesome, thank you Dillon for implementing and Olivier for suggesting!. Being able to record notes related to tasks allows me to organize knowledge in an intuitive way rather than keeping a bunch of separate files/sections in a document.

This plugin is just amazing, and keeps getting better 😄
