### ISSUE TITLE
Optionally include House Tabs + Redirect Scrolls for Redirected Tablets

### ISSUE THREAD

**Issue by SomeZer0** [dillydill123/inventory-setups#35]
When filtering the bank, I think it would be nice to have regular House Tabs & Redirect Scrolls included in the results when a setup includes a redirected teleport tab. (as a toggle)

**Comment by dillydill123** [comment]
Hmm, I'm not so sure about this. It's a lot of extra logic to check for specific teleport tabs and then attempt to check every item in the bank when filtering. I think you could just have the house tab and redirect scroll as part of the setup as a work around for now. Or perhaps Bank Tags might be better for a situation like this. I'll consider it more though and think about the implementation.

One potential solution I've thought of is adding a list of "additional filtered items" to each setup that would show up when bank filtering. This is so it wouldn't clutter up the setup and would be generic for any situation.

**Comment by SomeZer0** [comment]
> One potential solution I've thought of is adding a list of "additional filtered items" to each setup that would show up when bank filtering. This is so it wouldn't clutter up the setup and would be generic for any situation.

This would be a better solution in my opinion.

**Comment by usa-usa-usa-usa** [comment]
> Hmm, I'm not so sure about this. It's a lot of extra logic to check for specific teleport tabs and then attempt to check every item in the bank when filtering. I think you could just have the house tab and redirect scroll as part of the setup as a work around for now. Or perhaps Bank Tags might be better for a situation like this. I'll consider it more though and think about the implementation.
> 
> One potential solution I've thought of is adding a list of "additional filtered items" to each setup that would show up when bank filtering. This is so it wouldn't clutter up the setup and would be generic for any situation.

I think this is a great solution. Would be a nice reminder for something like a blowpipe with X-type of darts in it.

**Comment by dillydill123** [comment]
This additional filtered items has been added to 1.8 which is available now. See here on how to use it: https://github.com/dillydill123/inventory-setups#additional-filtered-items

**Comment by usa-usa-usa-usa** [comment]
> This additional filtered items has been added to 1.8 which is available now. See here on how to use it: https://github.com/dillydill123/inventory-setups#additional-filtered-items

Is there a technical reason why we can't right click the empy `Additional Filtered Items` and `update from search`?

**Comment by dillydill123** [comment]
I don't know why I didn't think of that. I'll add that in.

**Comment by dillydill123** [comment]
Added that in as well.
