### ISSUE TITLE
Could we somehow store prepot options?

### ISSUE THREAD

**Issue by jachymb** [dillydill123/inventory-setups#36]
It would be nice to have a checklisk of things to prepot (potions, angler, imbued heart,...)  for each setup. The proposed notes section in #34 could do the trick so this may perhaps be a duplicate.

**Comment by dillydill123** [comment]
Yeah I think this is another good use case for the notes section. I’ll add this eventually :)

**Comment by dillydill123** [comment]
Notes feature has been added to 1.7 and is available now.
