### ISSUE TITLE
Is it possible to add a similar option as this, for the rune pouch?

### ISSUE THREAD

**Issue by WaFFlzz** [dillydill123/inventory-setups#37]
At the moment, unless im doing something wrong, its only possible to update your rune pouch contents by updating the entirety of the setup. which is really annoying and ive ran into this issue so many times switching up my rune pouch. 
![image](https://user-images.githubusercontent.com/65757799/87112926-1cc8c480-c23b-11ea-8d77-87eeca3b822e.png)

**Comment by dillydill123** [comment]
You can update the rune pouch by right clicking and updating from inventory if you have the rune pouch in the same slot and with the updated runes. Have you tried this? Take a look at the gif here: https://github.com/dillydill123/inventory-setups#rune-pouch

**Comment by WaFFlzz** [comment]
Omg! life saver. i have been trying to update the rune pouch from the actual runes, maybe add an option to update individual runes, but definitely not necessary now that i know this.

**Comment by dillydill123** [comment]
I think the reason why I didn't add this originally is because you could technically have an "invalid" rune pouch with that feature. For example the plugin won't allow more than one rune pouch in the setup. But I don't think that would be a problem to be honest. I can look into it some more, but this feature should fill the need for the most part.

**Comment by dillydill123** [comment]
![image](https://user-images.githubusercontent.com/15637422/87863584-65166f80-c92a-11ea-9a57-3955e0a06339.png)

This is my current progress. As you can see you can have an "invalid" runepouch now. I don't see any harm though :D

**Comment by dillydill123** [comment]
this feature has been added to 1.7 and is available now.
