### ISSUE TITLE
Can you make a toggle or something to change how degradable items highlight?

### ISSUE THREAD

**Issue by WaFFlzz** [dillydill123/inventory-setups#38]
Like this setup here, the ahrims robetop is not highlighted, with the "Enable highlighting for variation differences" option ticked off, but neither is the stamina potion. 
![image](https://user-images.githubusercontent.com/65757799/87113282-e50e4c80-c23b-11ea-809a-62fc9d86e02a.png)
But in this screenshot, obviously, nothing is highlighted, meaning if you use the bank filter option the ahrims does not show up at all, which is annoying because you have to go back to your unfiltered bank and collect the items. 
![image](https://user-images.githubusercontent.com/65757799/87113457-446c5c80-c23c-11ea-922a-20336b774d79.png)
And heres an additional example of the primary use of this new proposed option, here i want to have a full stamina potion, and i want to be notified if its not a full stamina potion, but also want only a 1 dose and not the shown 2 dose stamina, and also want my ahrims to show up in the bank filters.
![image](https://user-images.githubusercontent.com/65757799/87113549-84cbda80-c23c-11ea-8fe0-aa15acf9a4b1.png)

**Comment by dillydill123** [comment]
Hey, I do have a plan for this. I want to make a way to add additional "filtered items" to the bank that would show up in the bank filter even if they are not in the setup. This is pretty much like bank tags. This would solve the bank filter issue.

I think I could use this filtered items set to decide if highlighting should be done. So in your bottom example, the degraded ahrim's pieces would be in the additional filtered list, while the stamina potion would not be. Meaning the stamina potion wouldn't appear in the filter, and would cause highlighting, while the ahrim's would be in the filter and not cause highlighting.

My only concern with this approach is how to specify things to add to the additional items filter. Right now, I'm thinking of adding a menu entry to items when holding down shift in the bank. This entry would be to add an item in the bank to the filtered list (or remove it). If you have any ideas regarding this let me know.

I'll start this eventually but have been busy with everything going on in the world :)

**Comment by Hydrox6** [comment]
It should be possible to add an option for variant items, like how Bank Tags currently does it. Either it could auto-tag known variant items, or just have an option to enable variant tagging on that slot for that item (maybe show an icon in the corner to let the user know it's variant tagged?)

**Comment by dillydill123** [comment]
I just want to make sure it's generic enough to put any item in there. For example some people like to prepot, or put tele tabs, etc.

**Comment by dillydill123** [comment]
The filtering issue has been alleviated in 1.8 with the additional items filter. However, I decided not to use this filter for deciding when to highlight, because it could be potentially misleading. An example is if you had a 1 dose potion to prepot in your additional filtered items, but you wanted only a 4 dose. If you had the 1 dose, it would not highlight even though it is not what is intended in the setup. I need a different solution for highlighting. I will make a new issue for this instead.
