### ISSUE TITLE
Save spellbook someone is on

### ISSUE THREAD

**Issue by ConradicalMel** [dillydill123/inventory-setups#4]
Maybe only save spellbook if runes are in the inventory?
![runelite_inventory_setup](https://user-images.githubusercontent.com/32449783/71701448-71c0e500-2d97-11ea-8eb4-292be595485e.png)

**Comment by dillydill123** [comment]
Spell book is varbit 4070
0 is standard
1 is ancients
2 is lunars
3 is arrceus

**Comment by dillydill123** [comment]
I'm not quite sure where to put the icon. I was thinking of replacing the rune pouch icon with the spellbook icon but then if the rune pouch is hidden it won't show up. Will come back to this later.

**Comment by dillydill123** [comment]
im deciding Not to add this because it would be awkward to fit in somewhere and I don’t think it provides that much value

**Comment by dillydill123** [comment]
Reopening because I'm indecisive and changed my mind. Also getting some feed back that this would be useful.

**Comment by dillydill123** [comment]
It's live now.
