### ISSUE TITLE
Suggestion: have the option to put the setups in alphabetical order

### ISSUE THREAD

**Issue by rafagracioso** [dillydill123/inventory-setups#41]
I believe it is a very good help if you have this option, making it easier to look beyond the search bar.

**Comment by dillydill123** [comment]
Current progress

![image](https://user-images.githubusercontent.com/15637422/87884872-4c1bc600-c9df-11ea-8540-cfcebcf0f980.png)

![image](https://user-images.githubusercontent.com/15637422/87884877-56d65b00-c9df-11ea-88e9-3974f01b0fbf.png)

Made it so more types can be added in the future.

**Comment by dillydill123** [comment]
Alphabetical feature has been added to 1.7 and is available now.
