### ISSUE TITLE
Store attack style for setup.

### ISSUE THREAD

**Issue by NathanQuayle** [dillydill123/inventory-setups#44]
I mostly use Inventory Setups to manage slayer tasks efficiently, but sometimes I forget what style monsters are weak to, so still have to go to the wiki. 

It would be great if we could save a weapon, with style. For example; Zammy Hasta with Crush.

**Comment by dillydill123** [comment]
I think this issue will be taken care of by the notes feature

**Comment by dillydill123** [comment]
Notes feature has been added to 1.7 and is available now.
