### ISSUE TITLE
Suggestion: Additionnal Filtering

### ISSUE THREAD

**Issue by ogermain5** [dillydill123/inventory-setups#49]
Would it be possible to have some extra items filtered for a setup? 

One reason for which this could be really useful is being able to filter pre-pot or teleport items for activities.
Example 1: In my ToB setup right now i have only 1 of each type of potion instead of my final inventory. Having extra filters would allow me to save the exact inventory i want + the prepots.
Example 2: For Chambers of Xeric, one would be able to add filter for gear required in all the different rooms.

Interface idea 1: Extra filters could be saved in a collapsable container between spellbook and notes?
Interface idea 2: Extra filters could be saved in a popup window with a button besides spellbook?

If this is what you meant in Issue #43, you can close this issue.
Thanks for your amazing works so far! :)

**Comment by dillydill123** [comment]
https://github.com/dillydill123/inventory-setups/issues/35 Check out the solution I've proposed for this one.

**Comment by dillydill123** [comment]
Added in 1.8 which is available now. See here how to use it: https://github.com/dillydill123/inventory-setups#additional-filtered-items
