### ISSUE TITLE
Suggestion: Mass export

### ISSUE THREAD

**Issue by MathieuDR** [dillydill123/inventory-setups#50]
I'm not sure where my data is stored/saved. But I would prefer to have a button to export all of my setups for safe-keeping.

**Comment by dillydill123** [comment]
Seems reasonable to add, maybe I can add a mass import button as well. If you log into runelite, the config is on the cloud somewhere. It's also stored locally. So you can log into runelite from a different computer and all the setups will be there.

**Comment by dillydill123** [comment]
I don't think I'll be adding this because u can easily copy your runelite settings from the folder itself:

C:\Users\<username>\.runelite\profiles\<profile>\settings.properties
or
C:\Users\<username>\.runelite\settings.properties for the default
