### ISSUE TITLE
Suggestion: Optional Spellbook

### ISSUE THREAD

**Issue by BRhodes** [dillydill123/inventory-setups#52]
A lot of times, I don't care what spellbook I am on for a setup but I still get the ugly red highlighting on my spellbook for the given setup. If there were someway to specify that no spellbook is required that'd be cool!

**Comment by dillydill123** [comment]
I think in the future I'd like to split the highlighting into 3 buttons - inventory, equipment, and spellbook. This should take care of that.

**Comment by dillydill123** [comment]
I had another idea, I could add a "None" spellbook type. This would make it so it doesn't highlight at all regardless of what spellbook the user had.

**Comment by BRhodes** [comment]
I think that was the best Idea I had as well to solve this one.

**Comment by dillydill123** [comment]
Added to 1.8 which is available now.
