### ISSUE TITLE
Weird graphical bug

### ISSUE THREAD

**Issue by usa-usa-usa-usa** [dillydill123/inventory-setups#53]
I am not sure what is causes this. I would be happy to show  someone as it happens all the time...

https://i.imgur.com/HCQoCMk.png

The way I resolve it is by taking the runelite out of focus, and putting it back in focus.

**Comment by dillydill123** [comment]
Do you have any steps to reproduce this?

**Comment by usa-usa-usa-usa** [comment]
SO one way to reproduce it is to teleport...

https://i.imgur.com/xYHfAni.gif

I do switch loadouts quite a bit because I turael skip for inferno tasks. I feel like it happens more frequently than just teleporting, This is just the only difinitive way I have found to reproduce it.

**Comment by usa-usa-usa-usa** [comment]
It also happens on a lesser jarring way when I swap around loadouts quickly....

https://i.imgur.com/ouT4v5V.gif

**Comment by dillydill123** [comment]
That's so odd... I can't reproduce it on my client which is the worst part. I'm guessing it might be related to the AsyncBufferedImages. What OS are you on? One more thing, when you teleport, it looks like another setup gets planted on top of the one your viewing. Does it seem like this is the case, or is it just random items?

**Comment by usa-usa-usa-usa** [comment]
I thought the same thing. It appears to be random though. If you look at the gif I posted, it looks like a rune pouch is faded in the background in like 5-6 different slots.

Runelite info: https://i.imgur.com/1Z1HanZ.png
OS Info: https://i.imgur.com/KSGBCnw.png

**Comment by usa-usa-usa-usa** [comment]
It appears that whenever any new map chunk renders, it is happening. Would re-installing the plugin do anything?

**Comment by dillydill123** [comment]
I doubt re-installing would do anything, but you can try. Your setups should be saved locally still, and if you log into RuneLite, they are saved on the cloud too. If you want to be extra safe, you can export each setup. I'd hate for you to lose your setup! One more thing, does this ever happen with the spellbook slot?

**Comment by usa-usa-usa-usa** [comment]
> I doubt re-installing would do anything, but you can try. Your setups should be saved locally still, and if you log into RuneLite, they are saved on the cloud too. If you want to be extra safe, you can export each setup. I'd hate for you to lose your setup! One more thing, does this ever happen with the spellbook slot?

https://i.imgur.com/eiujwbm.png

**Comment by usa-usa-usa-usa** [comment]
So breakthrough! I have pinned it down to an alpha channel on the highlighting color.

https://i.imgur.com/ZRWxl08.gif

**Comment by dillydill123** [comment]
Hey, glad you were able to figure it out. I'm not really sure what I should do here. I can try to see why the opacity breaks it, but I don't have any fancy logic regarding the color.. I could force the opacity to be 255? Not sure.

**Comment by usa-usa-usa-usa** [comment]
> Hey, glad you were able to figure it out. I'm not really sure what I should do here. I can try to see why the opacity breaks it, but I don't have any fancy logic regarding the color.. I could force the opacity to be 255? Not sure.

I'd imagine it's a limitation in the Java UI elements? If that's the case, that's what I would do. IDK if you can remove opacity from the runelite color selector as a whole. I believe there are some legacy runelite features that don't yet support opacity and they are working towards moving all color selections over to it.
