### ISSUE TITLE
Ability to filter bank interface from the 'setup' setup interface

### ISSUE THREAD

**Issue by usa-usa-usa-usa** [dillydill123/inventory-setups#54]
If I click the 'view setup' icon on a setup, the bank filters perfectly. And the panel shows my setup.

However, if I re-filter my bank through a core tag, tag tab, or something like that. The panel stays activated on the setups plugin, but the bank is now showing something different. 

To get back to the setup filter, I have to go back to the main 'Inventory Setups' panel, and re-click the 'view setup' button to get the bank to re-filter itself.

It would be great if there was a filter button directly on the setup interface.

**Comment by dillydill123** [comment]
There's a key bind you can setup in the config for refiltering. 

![image](https://user-images.githubusercontent.com/15637422/93007685-566ac400-f539-11ea-986a-3b6560373967.png)

Is this what you're looking for?

**Comment by dillydill123** [comment]
Also, you can right click the equipment icon and try refreshing the setup from there:

https://github.com/dillydill123/inventory-setups#overview-panel

**Comment by usa-usa-usa-usa** [comment]
That's awesome. Thanks for you're responsiveness on this plugin! Probably the best plugin-hub plugin out there.
