### ISSUE TITLE
Suggestion: Ability to remove an item

### ISSUE THREAD

**Issue by EdwardSalter** [dillydill123/inventory-setups#55]
After making heavy use of this plugin over the last few months I have found one critical feature to be missing: the removal of an item from a setup from within the editor.
Quite often I have found that I will tweak my inventory setup whilst on a slayer task and realised that I perhaps didn't need that prayer potion after all for instance.
At the minute, the only way to remove an item from the setup is to move the item to another inventory slot and then choose _update slot from inventory_ thus removing the item.

It would be a lot more user-friendly to include a right-click menu item on the slot that lets you just remove the item straight away replacing it with a blank slot.

**Comment by dillydill123** [comment]
Seems reasonable. Will add this in. Thanks for the suggestion.

**Comment by dillydill123** [comment]
Added in 1.8
