### ISSUE TITLE
Suggestion: Ability to set quick-prayer

### ISSUE THREAD

**Issue by EdwardSalter** [dillydill123/inventory-setups#56]
I am not sure if this is technically possible or not but it would be very useful if we could set up quick-prayers in this interface and then have it highlight if it is not set in the same manner as the equipment slots.
This would be super useful to prevent accidents during bossing where the quick-prayer wasn't set ahead of time for instance.

I know that the notes section could potentially be used for this but it is not as obvious when this has not been set.

**Comment by dillydill123** [comment]
I think it's technically possible, but I'd prefer to just have this be something specified in the notes section. Maybe I can do this with a toggle in the future. But at the current moment I'm not keen on it.

**Comment by dillydill123** [comment]
I think this is better just as a note in the notes section.
