### ISSUE TITLE
Setups dont saving the changes

### ISSUE THREAD

**Issue by oeg91** [dillydill123/inventory-setups#58]
I usually play 2 acc at the same time (regular and iron), when i do any changes on any setup, it doesnt save these changes when i open runelite again a couple of hours/days later.

**Comment by dillydill123** [comment]
Do you log into runelite with each account? Sometimes with RL logins you may have to wait some time for the config to get sync'd to the cloud.

**Comment by oeg91** [comment]
> Do you log into runelite with each account? Sometimes with RL logins you may have to wait some time for the config to get sync'd to the cloud.

Yes im logged in runelite when im playing both. I realise i have to close the client i just modify to get saved. I.E: i have client 1 and 2 open, i modify something on the client 1, then i have to close it first. If i close client 2 first, the changes doesnt saved

**Comment by dillydill123** [comment]
It might be better to log into accounts separately, e.g., use a different email for the iron and main.
