### ISSUE TITLE
Bug: Can't add new inventory setups

### ISSUE THREAD

**Issue by ConstantijnCrijnen** [dillydill123/inventory-setups#61]
I've never used this plugin before, but I followed the readme exactly yet it doesn't work.

Bug description:
First, I open the "inventory setups" tab.
Tab is opened and it says "Inventory Setups", "Create an inventory setup.".
I click on the green plus on the top right hand of the tab.
"Add New Setup" window opens.
I enter a random name and click "OK"
The "Add New Setup" window closes but nothing happened. The list is still empty and says "Inventory Setups", "Create an inventory setup.".

I can repeat this however much I like, I also restarted RL multiple times.

I'm using a 2019 macbook pro with the newest version of Catalina.

Am I missing something?
Thanks in advance!

**Comment by asherbasher** [comment]
You're supposed to get everything set up in your equipped gear and inventory first, then you add the setup. Sounds like you're trying to add an empty setup?

**Comment by joefromkokomo** [comment]
I have all my hydra gear and inventory and after i Add a new inventory set up and type in the name, nothing happens.

**Comment by dillydill123** [comment]
I can't seem to replicate this unfortunately, but it sounds like there is an issue with new users potentially. I will see if I can replicate it by deleting my local properties and starting as a "fresh" user.

**Comment by dillydill123** [comment]
I've identified the issue. I was able to replicate it by being a first time user. I will have a PR to fix this very soon. Hopefully it will be merged quickly. Thanks for making this issue!

**Comment by dillydill123** [comment]
The fix has been merged. Please let me know if the bug is still present, otherwise close this ticket :)

**Comment by ConstantijnCrijnen** [comment]
Thanks @dillydill123 ! It now works! And @asherbasher of course I didn't try it with no gear on :D
