### ISSUE TITLE
Unable to add a new set up

### ISSUE THREAD

**Issue by joefromkokomo** [dillydill123/inventory-setups#62]
First time using the plugin... Ofc i have gear equipped inventory full for hydra - add new setup- name setup- nothing happens. Simply doesnt work maybe its not detecting my items? I have a lot of other plug ins, could other plug ins disrupt this one?

**Comment by dillydill123** [comment]
What platform are you on?

**Comment by dillydill123** [comment]
I've identified the issue and will be making a PR to fix it very soon. 1.8.1 will have the fix.

**Comment by dillydill123** [comment]
The fix has been merged and is available now. Please let me know if you still cannot create setups, otherwise you can close this issue.

**Comment by joefromkokomo** [comment]
It works now thanks!
