### ISSUE TITLE
Bug: Hotkeys not working?

### ISSUE THREAD

**Issue by asherbasher** [dillydill123/inventory-setups#63]
Haven't used the hotkeys before but I just tried to assign a key and neither of them seem to be doing anything. I tried using a few different keys and nothing was happening.

Here's my settings:
![7lI1GbVZMW](https://user-images.githubusercontent.com/10160470/97332328-42bdb780-1872-11eb-9f4c-9c0ffb5dace5.png)

Went into a setup and tried to use the "Filter bank" hotkey but nothing happened.

**Comment by dillydill123** [comment]
I'm not having any issues with it at the moment. 

![xdsQboWIax](https://user-images.githubusercontent.com/15637422/97335109-d469fc80-1853-11eb-9076-cf6d3a672314.gif)

Can you try with the on screen keyboard?

**Comment by asherbasher** [comment]
![Vy3Mzi6Mou](https://user-images.githubusercontent.com/10160470/97339810-f1fe8c80-187a-11eb-86a1-48e77189fef6.gif)

**Comment by dillydill123** [comment]
Unfortunately I am unable to reproduce. I tried setting caps and numlock on and off to see if it's something to do with that. Is there anything set on your keyboard (sticky keys, mouse keys, etc..) that could potentially be the issue? I'll keep trying to reproduce in the meantime

**Comment by asherbasher** [comment]
I don't use any of those things or anything irregular I can think of. I always have num lock on but as you said that didn't change anything. I also tried turning bank tags off but that didn't do anything either.

**Comment by asherbasher** [comment]
Hmm, looks like it's working after a simple restart of RuneLite.

**Comment by dillydill123** [comment]
Let me know if this happens again and you can replicate it.
