### ISSUE TITLE
Bank Filtering not working properly with graceful

### ISSUE THREAD

**Issue by Nismm** [dillydill123/inventory-setups#67]
With the latest update graceful is no longer showing in bank filter without fuzzy turned on even with the correct graceful in the item slot (Tested with purple graceful)

**Comment by xlrc** [comment]
As Nismm said, same has happened for me. Also has stopped loading tree run payment items such as 'papayas', 'coconuts' etc. I haven't made any changes to this preset and it's worked perfectly for months up until now :)

**Comment by tsweeney256** [comment]
@Nismm you need to mark your graceful set as 'fuzzy' now with the latest version that was released. This worked for my green graceful set.

**Comment by dillydill123** [comment]
Hey guys, thanks for making the issue. When refactoring the code for the fuzzy filtering, I cut out an important line by mistake. I am testing my fix and it appears to be working. I'll have an update out soon with the fix once I do some additional sanity testing :)

**Comment by dillydill123** [comment]
By the way, you should **not** have to mark graceful as fuzzy when this fix is in. It should work just like before.

**Comment by dillydill123** [comment]
PR was merged and this should be available now in 1.9.1. Please let me know if you notice any issues!
