### ISSUE TITLE
Noted items not included in filtered results anymore

### ISSUE THREAD

**Issue by tsweeney256** [dillydill123/inventory-setups#68]
Since the new fuzzy filtering change, noted items are no longer being filtered in the bank results. Marking the items as 'fuzzy' does not help. I can work around this by replacing the noted items with their unnoted counterpart in the inventory setup, but that's not very ideal. This is particularly troublesome for farm runs.

This problems exists with or without the Bank Tags plugin enabled.

**Comment by dillydill123** [comment]
![image](https://user-images.githubusercontent.com/15637422/103100916-f1684500-45e2-11eb-9d1e-cad81836f18d.png)

I have fixed the issue. Will be making a PR soon once I do some additional testing to make sure I have not broken anything else. Thanks for making the issue!

**Comment by dillydill123** [comment]
PR was merged and should be available in 1.9.1 now. Please let me know if there are any issues. Thanks again for letting me know of this bug!
