### ISSUE TITLE
'No stack difference' no longer recognizing various item differences

### ISSUE THREAD

**Issue by DonMcDirty** [dillydill123/inventory-setups#70]
Including 
- degradation differences  on Barrows items
- charge differences on jewelry
- potion dosage differences. 

This is a recent issue within the past couple days with what I think was changes to the filtering system. This appeared the same time as the issue with graceful that was previously reported, but since appears to be fixed.

**Comment by dillydill123** [comment]
There is a new fuzzy filtering system that replaced the old variation differences. It's like variation differences except for individual slots instead. Please right click a slot on the inventory or equipment panels and select "Toggle Fuzzy" This will make it so it considers these items the same.

https://github.com/dillydill123/inventory-setups#fuzzy-difference

**Comment by DonMcDirty** [comment]
I understand it now, thank you.
