### ISSUE TITLE
Ignore order of runes in rune pouch

### ISSUE THREAD

**Issue by orlp** [dillydill123/inventory-setups#72]
The order of the runes in the rune pouch are essentially never significant so any order should be accepted and not marked as missing/erroneous if it doesn't match the order in the setup.

**Comment by dillydill123** [comment]
You are correct, and this is actually how I've implemented it in the plugin.

![image](https://user-images.githubusercontent.com/15637422/103157423-9f5d2600-4780-11eb-99ac-e1ca4686223c.png)

You can see that I have death -> water -> bloods but the setup is bloods -> death -> water. You may have found a bug if this is not the case for you. Can you post the setup and the options you have selected for that setup? I am unable to reproduce the issue.

**Comment by orlp** [comment]
My bad, it was actually stack differences that caused it. Is it possible to disable highlighting stack differences just for the rune pouch or on a per-slot basis?

**Comment by dillydill123** [comment]
per-slot basis is definitely something I'm interested in. I recently did this for variation differences. For now, maybe you can use less than stack differences and have just 1 rune of each type in the rune pouch for the setup?

**Comment by orlp** [comment]
I think the rest of the setup can work with less-than stack differences, but that's just in this particular scenario. I will close this erroneous request and add a new issue just for per-slot stack difference settings.
