### ISSUE TITLE
Toggle Fuzzy is not an option for Additional Filtered Items

### ISSUE THREAD

**Issue by KillerPoPTarT** [dillydill123/inventory-setups#74]
The new Toggle Fuzzy option is awesome, but you are unable to set it for items added to the Additional Filtered Items section. I commonly put the teleport crystal and necklaces in that section and would love the ability to add the fuzzy filter to those items.

**Comment by dillydill123** [comment]
I'll be looking to add this in at some point. I made some poor design choices when I first implemented additional filtered items so I will need to refactor some things I think.

**Comment by dillydill123** [comment]
Added in 1.10. Please let me know if u encounter any issues
