### ISSUE TITLE
cant "update slot from search" rada blessing 3

### ISSUE THREAD

**Issue by botanicvelious** [dillydill123/inventory-setups#75]
there is no rada blessing 3 in the search

**Comment by dillydill123** [comment]
Unfortunately none of the hard diary items are showing up in the search. There's nothing I can do because it's a RuneLite API that provides the search.

**Comment by botanicvelious** [comment]
You could use ItemVariationMapping.map(itemId) so that it uses the base item always rather then the specific version maby? The list is at https://github.com/runelite/runelite/blob/master/runelite-client/src/main/resources/item_variations.json looks like rada's blessing has all the variations as well

**Comment by dillydill123** [comment]
The problem with that is any potion will default to a specific dose, or amulets to a specific charge. I'd like to avoid specific exceptions. What you can do is toggle fuzzy on the ammo slot. This will make it so any of the blessings will count..

**Comment by botanicvelious** [comment]
There is no toggle fuzzy tho on "additional filtered items"

**Comment by dillydill123** [comment]
toggle fuzzy has been added to additional filtered items
