### ISSUE TITLE
Cannonballs not fuzzy

### ISSUE THREAD

**Issue by johnwhall** [dillydill123/inventory-setups#78]
It would be helpful for granite cannonballs to be considered fuzzy versions of regular cannonballs (and vice-versa).

**Comment by dillydill123** [comment]
Seems reasonable. I use RuneLite API to provide fuzzy versions of items actually, so I am surprised this is not in there. I think I can add my own additional set of mapped IDs to fix an issue like this.

**Comment by dillydill123** [comment]
I think this would be better to ask RuneLite to map cannonballs and granite cannonballs to be fuzzy in their API. If this is still a problem, I can make an issue or PR that way it would work in Inventory Setups as well.
