### ISSUE TITLE
Favorites System Suggestion

### ISSUE THREAD

**Issue by Dildenslatt** [dillydill123/inventory-setups#79]
I use this plugin quite frequently for many different activities around the game (perhaps a little **too** frequently), and as a result, I find myself sifting through my setups to find exactly what I'm looking for, even with alphabetical sorting. I suggest adding some sort of favorites system that would function independent of other sorting features. I believe this system should include some sort of visual indication of which setups have been favorited, both in compact and in standard mode, but more importantly, it should enable favorited setups to appear at the top of both sorted and unsorted setup lists. 
This would solve the issue of being forced to choose between easily accessing your most frequently used setups with custom/non-alphabetical sorting and efficiently accessing those less frequently used/situational setups with alphabetical sorting. While the search bar does alleviate this issue by a considerable degree, I believe that a favorites system would make day-to-day interactions with this plugin just that much more intuitive.

**Comment by dillydill123** [comment]
Hey, I created an issue for some more sorting options a while ago [here](https://github.com/dillydill123/inventory-setups/issues/42). The main problem is that I had no space to add a favorites button to the panel, but now there is space thanks to the variation and stack differences buttons being removed (slot specific now). Let me know if you have any ideas for sorting
