### ISSUE TITLE
Bank filtering does not persist after entering and exiting the new "show worn items" interface

### ISSUE THREAD

**Issue by asherbasher** [dillydill123/inventory-setups#8]
![E38nUauqYI](https://user-images.githubusercontent.com/10160470/72223266-c6691a80-3564-11ea-9667-8f55d6cf805c.gif)

**Comment by dillydill123** [comment]
Nice find. It looks like bank tags hasn't solved this issue yet either. I'll take a look.

**Comment by dillydill123** [comment]
Pushed a fix recently. It was trickier than I expected but it's working on my end. Will be in the next release.
