### ISSUE TITLE
Locked rune pouch does not cause rune pouch to show up

### ISSUE THREAD

**Issue by dillydill123** [dillydill123/inventory-setups#80]
![image](https://user-images.githubusercontent.com/15637422/106851700-bbf45400-6684-11eb-95ff-0124954b8316.png)

The rune pouch with trover attachment does not cause the runepouch panel to show up

**Comment by AFluffyWizard** [comment]
I'm experiencing the same issue and just unlocked my rune pouch solely because of this. It's so annoying how for each new setup I make, I have to manually add the runes in the "Additional Filtered Items" section. Valve pls fix

**Comment by dillydill123** [comment]
Hey, I actually wrote some code already to try to fix this bug, but I wasn't able to test it and haven't come back to it since. Are you able to test this for me? I can provide some instructions.

**Comment by dillydill123** [comment]
BTW, there are some temporary fixes for this. You can use the update from search feature to add a regular rune pouch to your setup, and then mark the slot as fuzzy. This should make it show up in the bank and also have the slots appear.

**Comment by AFluffyWizard** [comment]
> BTW, there are some temporary fixes for this. You can use the update from search feature to add a regular rune pouch to your setup, and then mark the slot as fuzzy. This should make it show up in the bank and also have the slots appear.

Ah I never thought of doing that, smart. And yeah if you want me to test something for you I'd be happy to. Let me know how I can help.

**Comment by dillydill123** [comment]
Sure, if you can checkout master and build and try making new setups with locked rune pouches that would be appreciated. If you can't build. I **highly** recommend making a backup of your settings.properties file (C:\Users\<User>\.runelite\settings.properties), and logging out of Runelite and removing Inventory Setups from your list of plugins (else two instances of the plugin will be running at once). I didn't change anything like persistent data that would cause problems with settings files, but always good to do this nonetheless so you don't accidentally lose your setups.

If you cannot build with Intellij, maybe there is a way I can provide a JAR file. I'm not sure. Either way I don't have an account with the locked rune pouch 🤷 so if you can test this for me it would be great!

**Comment by dillydill123** [comment]
Finally was able to test and the PR was merged.
