### ISSUE TITLE
sorting/organization

### ISSUE THREAD

**Issue by aCosmicSalmon** [dillydill123/inventory-setups#81]
Just add the ability to have folders or lil sandwich menus that we can open and close for better sorting. for example farming folder/menu bossing folder and maybe another one inside that for specific things like slayer boss or GWD etc endless possibility's plus i like to have some sorting for easy gear

**Comment by dillydill123** [comment]
I'm not against the idea but I am not sure how it should look. The best I can think of are collapsible menus. I also want this to be optional, so maybe a sorting mode would make the most sense? I will consider this for sure
