### ISSUE TITLE
[Suggestion] Groups

### ISSUE THREAD

**Issue by UhWatchMe** [dillydill123/inventory-setups#82]
Hi I'd like to make a suggestion to add groups

It'd look like this

1. Slayer (Main can be minimised and expanded)
 1.1 Dust devils (Only shown when expanded)
 1.2 Hellhounds (Only shown when expanded)

2 Farming (Main can be minimised and expanded)
 2.1 Herb run (Only shown when expanded)
 2.2 Tree run (Only shown when expanded)

I'm not sure how to show this in bank when right clicking worn items.

**Comment by dillydill123** [comment]
It's been a while, but I've been working on some infrastructure to make groups/sections possible.

**Comment by UhWatchMe** [comment]
> It's been a while, but I've been working on some infrastructure to make groups/sections possible.

It's been a while sincve the comment, do you have any updates on this? I think grouping on the panel right would be a great first step and worry later about it ingame.

**Comment by dillydill123** [comment]
A lot has gone on but I've made some progress, mostly on the technical side. It will still be some time before I can have something ready for this. There are a few changes I will have to make to the plugin in order to allow groups to work. One big one is I'll have to disallow setups with the same name. I'm going to use the name as the identifier within groups.

**Comment by dillydill123** [comment]
See here for an update

https://github.com/dillydill123/inventory-setups/issues/120#issuecomment-1166915096

**Comment by UhWatchMe** [comment]
> See here for an update
> 
> [#120 (comment)](https://github.com/dillydill123/inventory-setups/issues/120#issuecomment-1166915096)

Hello there again, it's been a long time! Man I opened Inventory Setups and saw the message of the update, appreciated man! Very well done for a first setup!
