### ISSUE TITLE
Export/Import Error

### ISSUE THREAD

**Issue by Big-ol-Corgi** [dillydill123/inventory-setups#83]
Hello,

Getting an error when I attempted to export and then import the same setup.

Here is the setup that was exported. I'm getting a "invalid setup data" when I attempt to import this. Some more info. I just created this setup, it was not a previous setup from before the fuzzy option was added.

{"inventory":[{"id":807,"name":"Iron dart","quantity":23348,"fuzzy":true,"stackCompare":"None"},{"id":-1,"name":"null","quantity":0,"fuzzy":true,"stackCompare":"None"},{"id":-1,"name":"null","quantity":0,"fuzzy":true,"stackCompare":"None"},{"id":2434,"name":"Prayer potion(4)","quantity":1,"fuzzy":false,"stackCompare":"None"},{"id":22109,"name":"Ava\u0027s assembler","quantity":1,"fuzzy":true,"stackCompare":"None"},{"id":-1,"name":"null","quantity":0,"fuzzy":true,"stackCompare":"None"},{"id":-1,"name":"null","quantity":0,"fuzzy":true,"stackCompare":"None"},{"id":2434,"name":"Prayer potion(4)","quantity":1,"fuzzy":false,"stackCompare":"None"},{"id":21183,"name":"Bracelet of slaughter","quantity":1,"fuzzy":true,"stackCompare":"None"},{"id":-1,"name":"null","quantity":0,"fuzzy":true,"stackCompare":"None"},{"id":-1,"name":"null","quantity":0,"fuzzy":true,"stackCompare":"None"},{"id":2434,"name":"Prayer potion(4)","quantity":1,"fuzzy":false,"stackCompare":"None"},{"id":21183,"name":"Bracelet of slaughter","quantity":1,"fuzzy":true,"stackCompare":"None"},{"id":-1,"name":"null","quantity":0,"fuzzy":true,"stackCompare":"None"},{"id":-1,"name":"null","quantity":0,"fuzzy":true,"stackCompare":"None"},{"id":-1,"name":"null","quantity":0,"fuzzy":true,"stackCompare":"None"},{"id":21183,"name":"Bracelet of slaughter","quantity":1,"fuzzy":true,"stackCompare":"None"},{"id":-1,"name":"null","quantity":0,"fuzzy":true,"stackCompare":"None"},{"id":-1,"name":"null","quantity":0,"fuzzy":true,"stackCompare":"None"},{"id":-1,"name":"null","quantity":0,"fuzzy":true,"stackCompare":"None"},{"id":-1,"name":"null","quantity":0,"fuzzy":true,"stackCompare":"None"},{"id":-1,"name":"null","quantity":0,"fuzzy":true,"stackCompare":"None"},{"id":13393,"name":"Xeric\u0027s talisman","quantity":1,"fuzzy":false,"stackCompare":"None"},{"id":24482,"name":"Open seed box","quantity":1,"fuzzy":true,"stackCompare":"None"},{"id":20724,"name":"Imbued heart","quantity":1,"fuzzy":true,"stackCompare":"None"},{"id":8013,"name":"Teleport to house","quantity":5,"fuzzy":true,"stackCompare":"None"},{"id":566,"name":"Soul rune","quantity":2000,"fuzzy":true,"stackCompare":"None"},{"id":12791,"name":"Rune pouch","quantity":1,"fuzzy":true,"stackCompare":"None"}],"equipment":[{"id":24444,"name":"Twisted slayer helmet (i)","quantity":1,"fuzzy":true,"stackCompare":"None"},{"id":13123,"name":"Ardougne cloak 3","quantity":1,"fuzzy":true,"stackCompare":"None"},{"id":12002,"name":"Occult necklace","quantity":1,"fuzzy":true,"stackCompare":"None"},{"id":6914,"name":"Master wand","quantity":1,"fuzzy":true,"stackCompare":"None"},{"id":9674,"name":"Proselyte hauberk","quantity":1,"fuzzy":true,"stackCompare":"None"},{"id":12612,"name":"Book of darkness","quantity":1,"fuzzy":true,"stackCompare":"None"},{"id":-1,"name":"null","quantity":0,"fuzzy":true,"stackCompare":"None"},{"id":12255,"name":"Armadyl robe legs","quantity":1,"fuzzy":true,"stackCompare":"None"},{"id":-1,"name":"null","quantity":0,"fuzzy":true,"stackCompare":"None"},{"id":21183,"name":"Bracelet of slaughter","quantity":1,"fuzzy":true,"stackCompare":"None"},{"id":13235,"name":"Eternal boots","quantity":1,"fuzzy":true,"stackCompare":"None"},{"id":-1,"name":"null","quantity":0,"fuzzy":true,"stackCompare":"None"},{"id":13128,"name":"Explorer\u0027s ring 4","quantity":1,"fuzzy":true,"stackCompare":"None"},{"id":22945,"name":"Rada\u0027s blessing 3","quantity":1,"fuzzy":true,"stackCompare":"None"}],"rune_pouch":[{"id":560,"name":"Death","quantity":4248,"fuzzy":false,"stackCompare":"None"},{"id":565,"name":"Blood","quantity":5000,"fuzzy":false,"stackCompare":"None"},{"id":555,"name":"Water","quantity":10000,"fuzzy":false,"stackCompare":"None"}],"additionalFilteredItems":{},"name":"Bursting, Nechs","notes":"","highlightColor":{"value":-476875,"falpha":0.0},"highlightDifference":true,"filterBank":true,"unorderedHighlight":false,"spellBook":0}

**Comment by dillydill123** [comment]
I'm not able to reproduce the issue. It imported just fine for me. What OS are you running?


![image](https://user-images.githubusercontent.com/15637422/109059838-b356d280-76b2-11eb-9ba6-d9c67e3b8a62.png) 
![image](https://user-images.githubusercontent.com/15637422/109059865-b94cb380-76b2-11eb-8e62-8bf8d30fab52.png)

**Comment by Big-ol-Corgi** [comment]
Interesting. I'm on Win 10.

**Comment by Big-ol-Corgi** [comment]
Might be something to do with corporate antivirus or something. Not a huge deal, I can just sync from my inventory, but thanks for looking into it.

**Comment by dillydill123** [comment]
Perhaps copy paste is acting different, or your plugin/client is not up to date? Both of these seem unlikely however. It is possible that there is a bug somewhere in the import code (I'm not a perfect programmer), so if you keep having this issue let me know.

Btw, you can use the login feature to sync your setups to the clouds. You can import your RuneLite settings (including inventory setup data) to your cloud settings and from there you can log into RuneLite with any computer and have all your setups available.

**Comment by Big-ol-Corgi** [comment]
Appreciate the detailed feedback!

I am already syncing my settings, but I appreciate you letting me know in case I wasn't.

I was mostly asking about this as I was trying to configure a barraging setup, but one individually for nechs and one for dust devils. I was trying to export and then import, but I can just configure one with the gear/inv on my character and then create a new loadout.

I've tried restarting my client now, and the error is persisting. I don't really know the cause but it's not a bit deal. Again, I think it's something related to the my company antivirus or firewall configuration, so unless someone else has a similar issue I wouldn't be too worried.

Thanks!

**Comment by cooperka** [comment]
I was having the same issue... I exported a setup then immediately tried to re-import it as a copy and it gave error `Invalid section data.`

Turns out I was in "section mode" instead of standard mode, so it was trying to import a SECTION instead of a SETUP. Easy fix was to switch back to standard mode and try again.
