### ISSUE TITLE
Client crashes after viewing inventory setup while in bank

### ISSUE THREAD

**Issue by ThatCrazyViking** [dillydill123/inventory-setups#87]
**Describe the bug**
The title is it. The client crashes completely after opening an inventory setup while also having the bank screen open. Just not every time. 

**To Reproduce**
1. Go to your bank and open it.
2. Click on 'View setup' with the following setup: {"inventory":[{"id":9739,"name":"Combat potion(4)","quantity":1,"fuzzy":false},{"id":9739,"name":"Combat potion(4)","quantity":1,"fuzzy":false},{"id":2434,"name":"Prayer potion(4)","quantity":1,"fuzzy":false},{"id":2434,"name":"Prayer potion(4)","quantity":1,"fuzzy":false},{"id":9739,"name":"Combat potion(4)","quantity":1,"fuzzy":false},{"id":9739,"name":"Combat potion(4)","quantity":1,"fuzzy":false},{"id":2434,"name":"Prayer potion(4)","quantity":1,"fuzzy":false},{"id":2434,"name":"Prayer potion(4)","quantity":1,"fuzzy":false},{"id":995,"name":"Coins","quantity":40,"fuzzy":false},{"id":-1,"name":"null","quantity":0,"fuzzy":false},{"id":-1,"name":"null","quantity":0,"fuzzy":false},{"id":-1,"name":"null","quantity":0,"fuzzy":false},{"id":-1,"name":"null","quantity":0,"fuzzy":false},{"id":-1,"name":"null","quantity":0,"fuzzy":false},{"id":-1,"name":"null","quantity":0,"fuzzy":false},{"id":-1,"name":"null","quantity":0,"fuzzy":false},{"id":-1,"name":"null","quantity":0,"fuzzy":false},{"id":-1,"name":"null","quantity":0,"fuzzy":false},{"id":-1,"name":"null","quantity":0,"fuzzy":false},{"id":-1,"name":"null","quantity":0,"fuzzy":false},{"id":13393,"name":"Xeric\u0027s talisman","quantity":1,"fuzzy":false},{"id":-1,"name":"","quantity":0,"fuzzy":false},{"id":-1,"name":"","quantity":0,"fuzzy":false},{"id":-1,"name":"null","quantity":0,"fuzzy":false},{"id":11806,"name":"Saradomin godsword","quantity":1,"fuzzy":false},{"id":8013,"name":"Teleport to house","quantity":1,"fuzzy":false},{"id":24478,"name":"Open herb sack","quantity":1,"fuzzy":false},{"id":12791,"name":"Rune pouch","quantity":1,"fuzzy":false}],"equipment":[{"id":11865,"name":"Slayer helmet (i)","quantity":1,"fuzzy":false},{"id":6570,"name":"Fire cape","quantity":1,"fuzzy":false},{"id":6585,"name":"Amulet of fury","quantity":1,"fuzzy":false},{"id":4151,"name":"Abyssal whip","quantity":1,"fuzzy":false},{"id":9674,"name":"Proselyte hauberk","quantity":1,"fuzzy":false},{"id":12954,"name":"Dragon defender","quantity":1,"fuzzy":false},{"id":-1,"name":"null","quantity":0,"fuzzy":false},{"id":9676,"name":"Proselyte cuisse","quantity":1,"fuzzy":false},{"id":-1,"name":"null","quantity":0,"fuzzy":false},{"id":22981,"name":"Ferocious gloves","quantity":1,"fuzzy":false},{"id":11840,"name":"Dragon boots","quantity":1,"fuzzy":false},{"id":-1,"name":"null","quantity":0,"fuzzy":false},{"id":11773,"name":"Berserker ring (i)","quantity":1,"fuzzy":false},{"id":22945,"name":"Rada\u0027s blessing 3","quantity":1,"fuzzy":false}],"rune_pouch":[{"id":561,"name":"Nature","quantity":100,"fuzzy":false},{"id":554,"name":"Fire","quantity":500,"fuzzy":false},{"id":-1,"name":"","quantity":0,"fuzzy":false}],"additionalFilteredItems":{"4162":{"id":4162,"name":"Rock hammer","quantity":1,"fuzzy":false},"19634":{"id":19634,"name":"Soul bearer","quantity":1,"fuzzy":false},"9811":{"id":9811,"name":"Farming cape(t)","quantity":1,"fuzzy":false},"9813":{"id":9813,"name":"Quest point cape","quantity":1,"fuzzy":false},"13116":{"id":13116,"name":"Bonecrusher","quantity":1,"fuzzy":false}},"name":"Slayer Melee Prayer","notes":"","highlightColor":{"value":-16711869,"falpha":0.0},"highlightDifference":true,"filterBank":true,"unorderedHighlight":false,"spellBook":0}
3. See error

Unfortunately, I can't purposefully reproduce this bug. It seems to only happen once after logging in for the first time each day.

**Expected behavior**
The game doesn't crash.

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.7.8.1
 - Launcher version: 2.1.8
 
**Additional context**
I have two separate logs of this event occurring, one from May 19th and one from May 22nd. Each one has the same problematic frame:

# Problematic frame:
# J 10702 C1 net.runelite.api.Item.getId()I (5 bytes) @ 0x03f75adb [0x03f75ac0+0x1b] 

May 19th: 

[hs_err_pid2792.log](https://github.com/runelite/runelite/files/6527174/hs_err_pid2792.log)

May 22nd:

[hs_err_pid1188.log](https://github.com/runelite/runelite/files/6527175/hs_err_pid1188.log)

**Comment by dillydill123** [comment]
Unfortunately I have not been able to reproduce the issue as well. However, the stack shows that this is perhaps coming from the Banked XP plugin? 

![image](https://user-images.githubusercontent.com/15637422/119364309-c01c9f80-bc7c-11eb-856f-ee4f9dcf0f3a.png)

It might be an interaction between the two plugins that are causing this. I'll keep trying to reproduce the issue in the meantime.

**Comment by dillydill123** [comment]
Looking more into it, I cannot find this com.bankxpvalue.BankXpValueItemOverlay... Or any of the classes. Do you know where this might be from? It doesn't seem to be from base RuneLite, and I couldn't find it in the BankedXp Plugin.

**Comment by dillydill123** [comment]
Is there anything useful from the logs? (C:\Users\Dillon\.runelite\logs)

**Comment by ThatCrazyViking** [comment]
I should also add that these crashes only started after the Clan Rework update last week. I've tried replicating this myself a few times since posting this, but I can't seem to do so myself as well. I have logged in every day since that update (sometimes multiple times per day), but this bug only occurred twice out of a dozen or so logins.

I do not know where the com.bankxpvalue.BankXpValueItemOverlay... is from, but it sounds like it should be from the BankedXp plugin.

Here are my logs from the two days that this bug occurred. 

[client_2021-05-19.0.log](https://github.com/dillydill123/inventory-setups/files/6533714/client_2021-05-19.0.log)

The crash seems to occur between these two lines:
2021-05-19 16:31:00 [Client] INFO  c.f.controller.FlippingPlugin - starting slot timers on login
2021-05-19 16:32:09 [RuneLite] INFO  net.runelite.client.RuneLite - RuneLite 1.7.8.1 (launcher version 1.6.0) starting up, args: none


[client_2021-05-22.0.log](https://github.com/dillydill123/inventory-setups/files/6533716/client_2021-05-22.0.log)

The crash seems to occur between these two lines:
2021-05-22 13:42:18 [Client] INFO  c.f.controller.FlippingPlugin - starting slot timers on login
2021-05-22 13:43:30 [RuneLite] INFO  net.runelite.client.RuneLite - RuneLite 1.7.8.1 (launcher version 1.6.0) starting up, args: none


From these, it almost looks like the FlippingPlugin might be involved somehow as well. It could be some sort of interaction between the FlippingPlugin and BankedXp plugin. I only posted it here since at first glance I assumed it was connected with the InventorySetup plugin.

**Comment by ThatCrazyViking** [comment]
The com.bankxpvalue.BankXpValueItemOverlay... is indeed from the Bank Xp Value plugin, lines 38 to 81 here: https://github.com/dseeler/bank-xp-value/blob/master/src/main/java/com/bankxpvalue/BankXpValueItemOverlay.java

**Comment by dillydill123** [comment]
I think the most likely case is the bankedXp plugin from looking at their code. It's possible an interaction between inventory setups and bankedXp is causing a nullptr somehow.... maybe during the filtering. Perhaps there needs to be some null checks in the plugin: https://github.com/dseeler/bank-xp-value/blob/master/src/main/java/com/bankxpvalue/BankXpValueItemOverlay.java#L61

**Comment by ThatCrazyViking** [comment]
That sounds reasonable. I'll open an issue over there. Thanks for everything.

**Comment by dillydill123** [comment]
Thanks for making the issue. If you figure out how to reproduce it consistently definitely let me know. That way we can confirm the source of the issue.
