### ISSUE TITLE
[Question] Where are inventory setups stored?

### ISSUE THREAD

**Issue by klvs** [dillydill123/inventory-setups#88]
I was looking for a hacky way to bulk-export all my setups and now find myself wondering where on my system setups are stored? I'll poke around the code more, but I'm not super familiar with the runelite API.

**Comment by dillydill123** [comment]
they are stored in settings.properties in your runelite folder.. e.g, C:\Users\<user>\.runelite\settings.properties 

Or if you are logged into RuneLite, it would be C:\Users\<user>\.runelite\profiles\<email>\settings.properties

The settings are stored with the key "inventorysetups.setups" So if you search this in the file you'll find the list of all inventory setups. You could use this to bulk export your setups, but importing only supports one at a time. So if you wanted to, you could replace the entire string in one profile with another to bulk replace all setups.

**Comment by dillydill123** [comment]
May I ask what reason you want to bulk export all setups? Do you just wish to make a backup? or send them to be eventually imported?

**Comment by jakerobers** [comment]
Just wanted to loop back onto this and say thank you. I'd just about die if I lost my inventory setups and am taking the extra precaution of doing regular backups on this file.

Fantastic work on this plugin!

**Comment by dillydill123** [comment]
@jakerobers FYI there is a “mass export” and “mass import” feature now. Please see the wiki for more details. This is also another way to backup your setups
