### ISSUE TITLE
Plugins causes bank search to break

### ISSUE THREAD

**Issue by rugg0064** [dillydill123/inventory-setups#89]
Without this plugin, and in the normal osrs client, hitting the bank search button, and hitting it a second time, it will close out of the search menu. At the moment with the plugin enabled, all the second click does it clear the search bar, but stays in search mode. To get out of the search mode you have to do something like click on a bank tab or close out of the bank.

**Comment by dillydill123** [comment]
Thanks for this. The search has always been wonky or caused problems. You can hit the enter key with empty search to clear it. But I can try to make it so it will close when u click the search button

**Comment by dillydill123** [comment]
Fixed now in v1.11
