### ISSUE TITLE
Runes in pouch do not persist after client restart

### ISSUE THREAD

**Issue by asherbasher** [dillydill123/inventory-setups#9]
![3BcRRZVRnr](https://user-images.githubusercontent.com/10160470/72223450-c538ed00-3566-11ea-8418-3a4959efdf8e.gif)

**Comment by dillydill123** [comment]
Did you use the update setup button (refresh looking symbol)? There's currently a bug where the config isn't updated when the update button is used. I made a fix for this that should be merged soon.  Try right clicking the rune pouch slot and select "Update Slot from Inventory" then try restarting your client. You may also need to wait a minute to allow the config to sync online if you are logged into a RuneLite account.

**Comment by asherbasher** [comment]
Ah yes, it was the update setup button which caused it. I wasn't aware you could right click the rune pouch and update from slot to set the runes but that does work and saves across restarts, so no issue here.

**Comment by dillydill123** [comment]
Cool glad that works! Thanks for making the issue anyways :)

**Comment by dillydill123** [comment]
FYI the PR was merged so the update setup button should correctly save the config.
