### ISSUE TITLE
Fuzzy toggle for cosmetic equipment variations

### ISSUE THREAD

**Issue by kblicharski** [dillydill123/inventory-setups#91]
Would it be possible to support this?

The fuzzy toggle does not work for cosmetic variations of certain items. The two that I have noticed are ancestral and twisted ancestral, and prospector's and golden prospector's.

I use these variants because I have obtained them, but a lot of my friends have not, and I would like my inventory setups to be generic so that they can simply import it and not need to modify it in order to get bank filtering to work properly.

**Comment by dillydill123** [comment]
Hey, actually I use the RuneLite ItemVariationMapping API to provide fuzzy matching.

See https://github.com/runelite/runelite/blob/master/runelite-client/src/main/resources/item_variations.json

This list is generated by the following:

https://github.com/abextm/runelite-cache-code-updater/blob/master/src/main/java/net/runelite/cache/codeupdater/apifiles/ItemVariationsUpdate.java#L47

I've considered creating my own supplemental list, but there could be arguments both ways on a lot of items (in the past granite cballs were brought up), so I've left it to the RuneLite API too decide what constitutes as fuzzy. I think you are better off making an issue with them.

I apologize for the inconvenience, and thanks for making the issue.

**Comment by dillydill123** [comment]
I've changed my mind and implemented this because of more requests. Please let me know if u have any issues.
