### ISSUE TITLE
Any way to recover setups from previous versions?

### ISSUE THREAD

**Issue by chunghus** [dillydill123/inventory-setups#92]
I haven't played OSRS in a few months, and to my chagrin after the RuneLite addition of the plugin hub all of my previous setups have been deleted. I don't suppose they were stored anywhere?

**Comment by dillydill123** [comment]
Check https://github.com/dillydill123/inventory-setups/issues/88. You may have a backup settings file that has them stored.

**Comment by chunghus** [comment]
That did the trick. Thanks!
