### ISSUE TITLE
Dragon Boots (g) do not work

### ISSUE THREAD

**Issue by orlp** [dillydill123/inventory-setups#93]
If I have Dragon Boots (g) in a filter and use bank filtering, the boots do not show up.

None of the variations I've tried for Dragon Boots normal, Dragon Boots (g), fuzzy or not, show up.

**Comment by dillydill123** [comment]
I wasn't able to reproduce this issue. Although I only have dragon legs (g) on my ironman.

![image](https://user-images.githubusercontent.com/15637422/124035774-01fedb00-d9cb-11eb-83c4-b54c6c42a156.png)

![image](https://user-images.githubusercontent.com/15637422/124035808-0dea9d00-d9cb-11eb-8bf8-c099f10ebfb1.png)

With fuzzy, the normal dragon platelegs will also show up. There's no special handling for any of these items, so I'm unsure of a possible cause atm. I will try to get someone else to help me reproduce the issue.

**Comment by orlp** [comment]
I have no idea what caused it before, because I tried fuzzy and non-fuzzy and it just refused to show up. But trying to reproduce now it works. So I'll just close this for now.
