### ISSUE TITLE
Add toggle for entries appearing in "Show worn items" right-click menu

### ISSUE THREAD

**Issue by OzzyCallooh** [dillydill123/inventory-setups#95]
As more inventory setup entries are added to the plugin, the right-click menu can become fairly crowded. If you have a lot (around 30 or more) and play in fixed mode, the last few might not even fit on the screen anymore.

Much like the bank filtering and highlight buttons, I propose another toggle button to be added which, when clicked, would prevent a setup from appearing in the right-click menu for the "Shorn worn items" button on the bank interface.

**Comment by dillydill123** [comment]
Hey thanks for the feedback. This has been a problem that many others have noted. I had a few ideas  to try and tackle this problem.

1) allow more lists to show up so all setups can be displayed.
2) add a favorite system and an option to only allow favorites to be displayed
3) Add option to only allow bank filtered setups to show up.

Ultimately I think I will implement a favorite system for setups and make it so you can choose to show all setups, favorited, or filtered setups in the show worn items menu.

**Comment by dillydill123** [comment]
Available now in v1.12
