### ISSUE TITLE
[Suggestion] Allow toggle fuzzy to show all (imbued) god capes, not limited to specific gods.

### ISSUE THREAD

**Issue by SpacemanRiff** [dillydill123/inventory-setups#97]
e.g. When toggle fuzzy is enabled on an Imbued Guthix Cape, it filters for all Imbued God Capes instead.

**Comment by dillydill123** [comment]
Hi, thanks for the suggestion. I actually use RuneLite API to determine Fuzziness. See https://github.com/dillydill123/inventory-setups/issues/91. Previously I wasn't against implementing such a feature, but there have been a number of requests for specific items, so I think I'll take a look into it.

**Comment by dillydill123** [comment]
Available now in v1.11. Let me know if u have any problems

**Comment by SpacemanRiff** [comment]
Appears to not be working for Imbued God Max Capes

**Comment by dillydill123** [comment]
I knew I would forget something! I forgot about the max cape variants. I'll make it so Imbued God Max Capes are the same as each other, but not the same as regular imbued god capes.

**Comment by dillydill123** [comment]
I've updated the plugin with max god capes and imbued max god capes. Please restart the client and try now.

**Comment by SpacemanRiff** [comment]
Yep, that works! Thanks much :)
